In [1]:
# Import the required packages
import pandas as pd
from os import path

pd.set_option("display.max_rows", 300)

## 1. Import Data:

Our first task is to import all the required data tables for our goal.

We are importing following tables:

1. Country wise medal counts of the Tokyo Olympics 2020: **`Tokyo_Medals_2020.csv`**
2. Country wise medal counts of the Rio Olympics 2016: **`Rio_Medals_2016.csv`**
3. Country wise medal counts of the London Olympics 2012: **`London_Medals_2012.csv`**

4. Country wise population table: **`Population_2020-21.csv`**
5. Country wise Covid and Vaccination Data **`Covid_Vaccination_Data.csv`**
6. Country wise GDP data **`GDP_Actual_Value.csv`**

In [2]:
# full path where data files are stored
dir_path = input("Enter the directory where data files are stored: " )

Enter the directory where data files are stored: /Users/tanuja/Documents/Germany/Jacobs University, Bremen/Study Material/Fall 2021/Data Management with Python/HomeWork/DMP/Final DMP/

In [3]:
df_tokyo = pd.read_csv(path.join(dir_path,"Tokyo_Medals_2020.csv"), header=0)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total  Rank By Total
0   Argentina           0             1             2      3             60
1     Armenia           0             2             2      4             47
2   Australia          17             7            22     46              6
3     Austria           1             1             5      7             33
4  Azerbaijan           0             3             4      7             33

In [4]:
df_rio = pd.read_csv(path.join(dir_path,"Rio_Medals_2016.csv"), header=0)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze
0    Algeria     0       2       0
1  Argentina     3       1       0
2    Armenia     1       3       0
3  Australia     8      11      10
4    Austria     0       0       1

In [5]:
df_london = pd.read_csv(path.join(dir_path,"London_Medals_2012.csv"), header=0)

df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold Medal  Silver Medal  Bronze Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35

In [6]:
df_population = pd.read_csv(path.join(dir_path,"Population_2020-21.csv"), header= 0)

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

  cca2            name    pop2021    pop2020    pop2050    pop2030    pop2019  \
0   AF     Afghanistan  39835.428  38928.346  64682.974  48093.578  38041.754
1   AL         Albania   2872.933   2877.797   2424.061   2786.974   2880.917
2   DZ         Algeria  44616.624  43851.044  60923.386  50360.749  43053.054
3   AS  American Samoa     55.100     55.191     53.581     54.728     55.312
4   AD         Andorra     77.355     77.265     76.118     77.925     77.142

     pop2015    pop2010    pop2000    pop1990    pop1980    pop1970     area  \
0  34413.603  29185.507  20779.953  12412.308  13356.511  11173.642   652230
1   2890.513   2948.023   3129.243   3286.073   2682.690   2150.707    28748
2  39728.025  35977.455  31042.235  25758.869  19221.665  14464.985  2381741
3     55.812     56.079     57.821     47.347     32.646     27.363      199
4     78.011     84.449     65.390     54.509     36.067     24.276      468

    Density  GrowthRate  WorldPercentage  rank
0   61.0757      1.0233           0.0051    37
1   99.9351      0.9983           0.0004   140
2   18.7328      1.0175           0.0057    34
3  276.8844      0.9984           0.0000   209
4  165.2885      1.0012           0.0000   202

In [7]:
df_covid_vac = pd.read_csv(path.join(dir_path,"Covid_Vaccination_Data.csv"), header= 0)

df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...
1                 NaN           NaN         NaN                  NaN  ...
2                 NaN           NaN         NaN                  NaN  ...
3                 NaN           NaN         NaN                  NaN  ...
4                 NaN           NaN         NaN                  NaN  ...

   female_smokers  male_smokers  handwashing_facilities  \
0             NaN           NaN                  37.746
1             NaN           NaN                  37.746
2             NaN           NaN                  37.746
3             NaN           NaN                  37.746
4             NaN           NaN                  37.746

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.5            64.83                    0.511
1                         0.5            64.83                    0.511
2                         0.5            64.83                    0.511
3                         0.5            64.83                    0.511
4                         0.5            64.83                    0.511

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN

[5 rows x 67 columns]

In [8]:
df_gdp = pd.read_csv(path.join(dir_path,"GDP_Actual_Value.csv"), header= 0, encoding="ISO-8859-1")

df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

  GDP, current prices (Billions of U.S. dollars)     1980     1981     1982  \
0                                            NaN      NaN      NaN      NaN
1                                    Afghanistan  no data  no data  no data
2                                        Albania    1.946    2.229    2.296
3                                        Algeria   42.346   44.372    44.78
4                                        Andorra  no data  no data  no data

      1983     1984     1985     1986     1987     1988  ...     2017  \
0      NaN      NaN      NaN      NaN      NaN      NaN  ...      NaN
1  no data  no data  no data  no data  no data  no data  ...   18.883
2    2.319     2.29    2.339    2.587    2.566     2.53  ...   13.053
3   47.529   51.513   61.132   61.535     63.3   51.664  ...  170.207
4  no data  no data  no data  no data  no data  no data  ...    2.993

      2018    2019    2020     2021     2022     2023     2024     2025  \
0      NaN     NaN     NaN      NaN      NaN      NaN      NaN      NaN
1   18.401  18.876  20.136  no data  no data  no data  no data  no data
2   15.147  15.283  14.828    16.77   18.012   18.931   20.026    21.15
3  175.367  171.07   147.6  163.812  168.195  172.094  173.719  174.376
4    3.217   3.155   2.858    3.213     3.46    3.659    3.851    4.017

      2026
0      NaN
1  no data
2   22.308
3  175.228
4    4.179

[5 rows x 48 columns]

---

## 2. Data Pre-processing

After having imported the dataset from _.csv_ files into Pandas _dataframe_, we perform pre-processing of the data before storing it in the MySQL database.

We divide the pre-processing steps into two major parts:
1. First we carry out some basic cleaning of all the datasets, which includes steps like dropping non-essential columns, checking column names and checking missing values.

2. Secondly, we normalise the country names across all the datasets by considering the country names in the `df_population` dataframe as reference.

### Part I - Basic Data Cleaning

We perform the following steps for the basic cleaning of the imported datasets:

1. Drop non-essential columns & rows and add essential columns to the dataset.
2. Remove whitespaces around the column names of the dataset. Also rename the column name if necessary.
3. Check for any missing values in the dataset and rectify them.
4. Clean the country names by removing special characters and digits.

We define the below functions to fix the column names, normalise the country names and checking of any missing values.

In [9]:
# Define a function to fix the column name of DataFrame

def fix_column_name(df):
    
    """
    This function checks and removes any whitespace
    before and after the column name. And replaces
    spaces between words with an underscore.
    
    Input:
        df: Pandas DataFrame
    
    Return:
        Pandas DataFrame
    
    """
    
    df.columns = [c.strip().replace(" ", "_") for c in df.columns]
    
    return None

In [10]:
# Define a function to check missing values in DataFrame

def find_total_missing_val_and_loc(df):
    
    """
    This function prints the total number of missing values
    in the given DataFrame for each column and returns the
    records with missing value. Otherwise, it returns "None".
    
    Input:
        df: Pandas DataFrame
    
    Return:
        Pandas DataFrame
    
    """

    missing_val = df.isnull().sum()
    
    if sum(missing_val):
        print(missing_val)
        return df.loc[df.isnull().T.any()]

    else:
        print("No missing values")
        return None

In [11]:
# Doubts
# Define a function to normalize the country name

def normalize_country_names(df, country_col):
    
    """
    Return the Unicode normal form of the strings of the
    Pandas Series with the name: country_col.
       
    Input:
        df: Pandas DataFrame
        country_col: string
    
    Returns
        df_tmp: Pandas Series
    """
    
    # Get the column which is having country name from the table
    df_tmp = df.copy() 
    country_names = df_tmp[country_col]

    # Replace `_` with whitespace
    country_names = country_names.str.replace("_", " ")

    # Remove parenthesis and any content and whitespace around it
    country_names = country_names.str.replace("\s*\(.*\)\s*", '',regex=True)
    
    # normalise the string values to remove symbols and diacritics
    norm_name = country_names.str.normalize('NFKD')
    norm_name = norm_name.str.encode('ascii',errors='ignore').str.decode('utf-8')

    df_tmp[country_col] = country_names
    
    return df_tmp

#### I. Basic cleaning of the `df_tokyo` dataframe:

In [12]:
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total  Rank By Total
0   Argentina           0             1             2      3             60
1     Armenia           0             2             2      4             47
2   Australia          17             7            22     46              6
3     Austria           1             1             5      7             33
4  Azerbaijan           0             3             4      7             33

In the above output, `df_tokyo` contains the column **`Rank by Total`**, which we do not need in our case.

Hence, we remove this column.

In [13]:
# Drop column "Rank by Total"
df_tokyo = df_tokyo.drop(columns="Rank By Total", axis=1)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7

Now, we fix the column names of the dataframe

In [14]:
# Fix column names of the dataframe
fix_column_name(df_tokyo)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7

Then, we check if there are any missing values

In [15]:
# Find any missing values
find_total_missing_val_and_loc(df_tokyo)

No missing values

Finally, we normalise the country names

In [16]:
# Clean the country names
df_tokyo = normalize_country_names(df_tokyo, "Country")

In [17]:
df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7

#### II. Basic cleaning of the `df_rio` dataframe:

In [18]:
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze
0    Algeria     0       2       0
1  Argentina     3       1       0
2    Armenia     1       3       0
3  Australia     8      11      10
4    Austria     0       0       1

In the above output, `df_rio`, do not contain the column **`Total`**.

Hence we are add this column.

In [19]:
# Add column "Total"
df_rio["Total"] = df_rio.iloc[:,1:3].sum(axis=1)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0

Now, we fix the column names of the dataframe

In [20]:
# Fix column names of the dataframe
fix_column_name(df_rio)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0

Then, we check if there are any missing values

In [21]:
# Find any missing values
find_total_missing_val_and_loc(df_rio)

No missing values

Finally, we normalise the country names

In [22]:
# Clean the country names
df_rio = normalize_country_names(df_rio, "Country")

In [23]:
df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0

#### III. Basic cleaning of the `df_london` dataframe:

In [24]:
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold Medal  Silver Medal  Bronze Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35

There is no need to add or remove any column here.

Now, we fix the column names

In [25]:
# Fix column names of the dataframe
fix_column_name(df_london)

df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35

Then, we check if there are any missing values

In [26]:
# Find any missing values
find_total_missing_val_and_loc(df_london)

No missing values

Finally, we normalise the country names

In [27]:
# Clean the country names
df_london = normalize_country_names(df_london, "Country")

In [28]:
df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35

#### IV. Basic cleaning of the `df_population` dataframe:

In [29]:
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

  cca2            name    pop2021    pop2020    pop2050    pop2030    pop2019  \
0   AF     Afghanistan  39835.428  38928.346  64682.974  48093.578  38041.754
1   AL         Albania   2872.933   2877.797   2424.061   2786.974   2880.917
2   DZ         Algeria  44616.624  43851.044  60923.386  50360.749  43053.054
3   AS  American Samoa     55.100     55.191     53.581     54.728     55.312
4   AD         Andorra     77.355     77.265     76.118     77.925     77.142

     pop2015    pop2010    pop2000    pop1990    pop1980    pop1970     area  \
0  34413.603  29185.507  20779.953  12412.308  13356.511  11173.642   652230
1   2890.513   2948.023   3129.243   3286.073   2682.690   2150.707    28748
2  39728.025  35977.455  31042.235  25758.869  19221.665  14464.985  2381741
3     55.812     56.079     57.821     47.347     32.646     27.363      199
4     78.011     84.449     65.390     54.509     36.067     24.276      468

    Density  GrowthRate  WorldPercentage  rank
0   61.0757      1.0233           0.0051    37
1   99.9351      0.9983           0.0004   140
2   18.7328      1.0175           0.0057    34
3  276.8844      0.9984           0.0000   209
4  165.2885      1.0012           0.0000   202

We only nead Country Name, and Population for 2020, and 2021.

Hence we drop the other columns.

In [30]:
df_population = df_population[["name","pop2021","pop2020"]]

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265

Now, we fix the column names of the dataframe

In [31]:
# Fix column names of the dataframe
fix_column_name(df_population)

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265

Then, we check if there are any missing values

In [32]:
# Find any missing values
find_total_missing_val_and_loc(df_population)

No missing values

Finally, we normalise the country names

In [33]:
# Clean the country names
df_population = normalize_country_names(df_population, "name")

In [34]:
df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265

We observe that population values are divided by 1000 in the _.csv_ file.

So, we multiply the values of both the population columns by 1000 to get the correct population numbers.

In [35]:
df_population['pop2021'] = df_population['pop2021'].apply(lambda x : x * 1000)
df_population['pop2020'] = df_population['pop2020'].apply(lambda x : x * 1000)

In [36]:
df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name     pop2021     pop2020
0     Afghanistan  39835428.0  38928346.0
1         Albania   2872933.0   2877797.0
2         Algeria  44616624.0  43851044.0
3  American Samoa     55100.0     55191.0
4         Andorra     77355.0     77265.0

#### V. Basic cleaning of the `df_covid_vac` dataframe:

In [37]:
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...
1                 NaN           NaN         NaN                  NaN  ...
2                 NaN           NaN         NaN                  NaN  ...
3                 NaN           NaN         NaN                  NaN  ...
4                 NaN           NaN         NaN                  NaN  ...

   female_smokers  male_smokers  handwashing_facilities  \
0             NaN           NaN                  37.746
1             NaN           NaN                  37.746
2             NaN           NaN                  37.746
3             NaN           NaN                  37.746
4             NaN           NaN                  37.746

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.5            64.83                    0.511
1                         0.5            64.83                    0.511
2                         0.5            64.83                    0.511
3                         0.5            64.83                    0.511
4                         0.5            64.83                    0.511

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN

[5 rows x 67 columns]

This dataframe has many columns. So lets see what are the column names in the table and keep only required columns

In [38]:
for i, c in enumerate(df_covid_vac.columns):
    print(i, c)

0 iso_code
1 continent
2 location
3 date
4 total_cases
5 new_cases
6 new_cases_smoothed
7 total_deaths
8 new_deaths
9 new_deaths_smoothed
10 total_cases_per_million
11 new_cases_per_million
12 new_cases_smoothed_per_million
13 total_deaths_per_million
14 new_deaths_per_million
15 new_deaths_smoothed_per_million
16 reproduction_rate
17 icu_patients
18 icu_patients_per_million
19 hosp_patients
20 hosp_patients_per_million
21 weekly_icu_admissions
22 weekly_icu_admissions_per_million
23 weekly_hosp_admissions
24 weekly_hosp_admissions_per_million
25 new_tests
26 total_tests
27 total_tests_per_thousand
28 new_tests_per_thousand
29 new_tests_smoothed
30 new_tests_smoothed_per_thousand
31 positive_rate
32 tests_per_case
33 tests_units
34 total_vaccinations
35 people_vaccinated
36 people_fully_vaccinated
37 total_boosters
38 new_vaccinations
39 new_vaccinations_smoothed
40 total_vaccinations_per_hundred
41 people_vaccinated_per_hundred
42 people_fully_vaccinated_per_hundred
43 total_boosters_per_hundred
44 new_vaccinations_smoothed_per_million
45 new_people_vaccinated_smoothed
46 new_people_vaccinated_smoothed_per_hundred
47 stringency_index
48 population
49 population_density
50 median_age
51 aged_65_older
52 aged_70_older
53 gdp_per_capita
54 extreme_poverty
55 cardiovasc_death_rate
56 diabetes_prevalence
57 female_smokers
58 male_smokers
59 handwashing_facilities
60 hospital_beds_per_thousand
61 life_expectancy
62 human_development_index
63 excess_mortality_cumulative_absolute
64 excess_mortality_cumulative
65 excess_mortality
66 excess_mortality_cumulative_per_million

We only need following columns:
* 2 location  >>(country name)
* 3 date
* 4 total_cases
* 5 new_cases
* 7 total_deaths
* 8 new_deaths
* 34 total_vaccinations
* 35 people_vaccinated
* 36 people_fully_vaccinated

In [39]:
df_covid_vac = df_covid_vac[["location", "date", "total_cases", "new_cases", "total_deaths", "new_deaths", 
                      "people_vaccinated", "people_fully_vaccinated"]]
df_covid_vac

,location,date,total_cases,new_cases,total_deaths,new_deaths,people_vaccinated,people_fully_vaccinated
0,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN
1,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN
2,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN
3,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN
4,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
134875,Zimbabwe,2021-11-17,133557.0,52.0,4699.0,1.0,NaN,NaN
134876,Zimbabwe,2021-11-18,133593.0,36.0,4699.0,0.0,3583256.0,2727175.0
134877,Zimbabwe,2021-11-19,133593.0,0.0,4699.0,0.0,3625221.0,2737278.0
134878,Zimbabwe,2021-11-20,133615.0,22.0,4699.0,0.0,3651820.0,2744192.0
134879,Zimbabwe,2021-11-21,133647.0,32.0,4699.0,0.0,3672011.0,2747693.0

In [40]:
df_unique_country_name = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])

df_unique_country_name

                         Country_Name
0                         Afghanistan
1                              Africa
2                             Albania
3                             Algeria
4                             Andorra
5                              Angola
6                            Anguilla
7                 Antigua and Barbuda
8                           Argentina
9                             Armenia
10                              Aruba
11                               Asia
12                          Australia
13                            Austria
14                         Azerbaijan
15                            Bahamas
16                            Bahrain
17                         Bangladesh
18                           Barbados
19                            Belarus
20                            Belgium
21                             Belize
22                              Benin
23                            Bermuda
24                             Bhutan
25                            Bolivia
26    Bonaire Sint Eustatius and Saba
27             Bosnia and Herzegovina
28                           Botswana
29                             Brazil
30             British Virgin Islands
31                             Brunei
32                           Bulgaria
33                       Burkina Faso
34                            Burundi
35                           Cambodia
36                           Cameroon
37                             Canada
38                         Cape Verde
39                     Cayman Islands
40           Central African Republic
41                               Chad
42                              Chile
43                              China
44                           Colombia
45                            Comoros
46                              Congo
47                       Cook Islands
48                         Costa Rica
49                      Cote d'Ivoire
50                            Croatia
51                               Cuba
52                            Curacao
53                             Cyprus
54                            Czechia
55       Democratic Republic of Congo
56                            Denmark
57                           Djibouti
58                           Dominica
59                 Dominican Republic
60                            Ecuador
61                              Egypt
62                        El Salvador
63                  Equatorial Guinea
64                            Eritrea
65                            Estonia
66                           Eswatini
67                           Ethiopia
68                             Europe
69                     European Union
70                     Faeroe Islands
71                   Falkland Islands
72                               Fiji
73                            Finland
74                             France
75                   French Polynesia
76                              Gabon
77                             Gambia
78                            Georgia
79                            Germany
80                              Ghana
81                          Gibraltar
82                             Greece
83                          Greenland
84                            Grenada
85                          Guatemala
86                           Guernsey
87                             Guinea
88                      Guinea-Bissau
89                             Guyana
90                              Haiti
91                        High income
92                           Honduras
93                          Hong Kong
94                            Hungary
95                            Iceland
96                              India
97                          Indonesia
98                      International
99                               Iran
100                              Iraq
101                           Ireland
102                       Isle of Man
103                            Israel
104                             Italy
105                           Jamaica
106                             Japan
107                            Jersey
108                            Jordan
109                        Kazakhstan
110                             Kenya
111                          Kiribati
112                            Kosovo
113                            Kuwait
114                        Kyrgyzstan
115                              Laos
116                            Latvia
117                           Lebanon
118                           Lesotho
119                           Liberia
120                             Libya
121                     Liechtenstein
122                         Lithuania
123                        Low income
124               Lower middle income
125                        Luxembourg
126                             Macao
127                        Madagascar
128                            Malawi
129                          Malaysia
130                          Maldives
131                              Mali
132                             Malta
133                  Marshall Islands
134                        Mauritania
135                         Mauritius
136                            Mexico
137              Micronesia (country)
138                           Moldova
139                            Monaco
140                          Mongolia
141                        Montenegro
142                        Montserrat
143                           Morocco
144                        Mozambique
145                           Myanmar
146                           Namibia
147                             Nauru
148                             Nepal
149                       Netherlands
150                     New Caledonia
151                       New Zealand
152                         Nicaragua
153                             Niger
154                           Nigeria
155                              Niue
156                     North America
157                   North Macedonia
158                   Northern Cyprus
159                            Norway
160                           Oceania
161                              Oman
162                          Pakistan
163                             Palau
164                         Palestine
165                            Panama
166                  Papua New Guinea
167                          Paraguay
168                              Peru
169                       Philippines
170                          Pitcairn
171                            Poland
172                          Portugal
173                             Qatar
174                           Romania
175                            Russia
176                            Rwanda
177                      Saint Helena
178             Saint Kitts and Nevis
179                       Saint Lucia
180  Saint Vincent and the Grenadines
181                             Samoa
182                        San Marino
183             Sao Tome and Principe
184                      Saudi Arabia
185                           Senegal
186                            Serbia
187                        Seychelles
188                      Sierra Leone
189                         Singapore
190         Sint Maarten (Dutch part)
191                          Slovakia
192                          Slovenia
193                   Solomon Islands
194                           Somalia
195                      South Africa
196                     South America
197                       South Korea
198                       South Sudan
199                             Spain
200                         Sri Lanka
201                             Sudan
202                          Suriname
203                            Sweden
204                       Switzerland
205                             Syria
206                            Taiwan
207                        Tajikistan
208                          Tanzania
209                          Thailand
210                             Timor
211                              Togo
212                           Tokelau
213                             Tonga
214               Trinidad and Tobago
215                           Tunisia
216                            Turkey
217                      Turkmenistan
218          Turks and Caicos Islands
219                            Tuvalu
220                            Uganda
221                           Ukraine
222              United Arab Emirates
223                    United Kingdom
224                     United States
225               Upper middle income
226                           Uruguay
227                        Uzbekistan
228                           Vanuatu
229                           Vatican
230                         Venezuela
231                           Vietnam
232                 Wallis and Futuna
233                             World
234                             Yemen
235                            Zambia
236                          Zimbabwe

From the above, we can see that the dataset also contains the below entries which are not names of a country.

* Africa
* Asia
* Europe
* European Union
* High income
* International
* Low income
* Lower middle income
* North America
* Oceania
* South America
* Upper middle income
* World

In [41]:
to_remove = ["Africa", "Asia", "Europe", "European Union", "High income", 
             "International", "Low income", "Lower middle income", 
             "North America", "Oceania","South America", "Upper middle income","World"]

for name in to_remove:
    df_covid_vac.drop(df_covid_vac[df_covid_vac['location'] == name].index, inplace = True)

df_unique_country_name = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])

df_unique_country_name

                         Country_Name
0                         Afghanistan
1                             Albania
2                             Algeria
3                             Andorra
4                              Angola
5                            Anguilla
6                 Antigua and Barbuda
7                           Argentina
8                             Armenia
9                               Aruba
10                          Australia
11                            Austria
12                         Azerbaijan
13                            Bahamas
14                            Bahrain
15                         Bangladesh
16                           Barbados
17                            Belarus
18                            Belgium
19                             Belize
20                              Benin
21                            Bermuda
22                             Bhutan
23                            Bolivia
24    Bonaire Sint Eustatius and Saba
25             Bosnia and Herzegovina
26                           Botswana
27                             Brazil
28             British Virgin Islands
29                             Brunei
30                           Bulgaria
31                       Burkina Faso
32                            Burundi
33                           Cambodia
34                           Cameroon
35                             Canada
36                         Cape Verde
37                     Cayman Islands
38           Central African Republic
39                               Chad
40                              Chile
41                              China
42                           Colombia
43                            Comoros
44                              Congo
45                       Cook Islands
46                         Costa Rica
47                      Cote d'Ivoire
48                            Croatia
49                               Cuba
50                            Curacao
51                             Cyprus
52                            Czechia
53       Democratic Republic of Congo
54                            Denmark
55                           Djibouti
56                           Dominica
57                 Dominican Republic
58                            Ecuador
59                              Egypt
60                        El Salvador
61                  Equatorial Guinea
62                            Eritrea
63                            Estonia
64                           Eswatini
65                           Ethiopia
66                     Faeroe Islands
67                   Falkland Islands
68                               Fiji
69                            Finland
70                             France
71                   French Polynesia
72                              Gabon
73                             Gambia
74                            Georgia
75                            Germany
76                              Ghana
77                          Gibraltar
78                             Greece
79                          Greenland
80                            Grenada
81                          Guatemala
82                           Guernsey
83                             Guinea
84                      Guinea-Bissau
85                             Guyana
86                              Haiti
87                           Honduras
88                          Hong Kong
89                            Hungary
90                            Iceland
91                              India
92                          Indonesia
93                               Iran
94                               Iraq
95                            Ireland
96                        Isle of Man
97                             Israel
98                              Italy
99                            Jamaica
100                             Japan
101                            Jersey
102                            Jordan
103                        Kazakhstan
104                             Kenya
105                          Kiribati
106                            Kosovo
107                            Kuwait
108                        Kyrgyzstan
109                              Laos
110                            Latvia
111                           Lebanon
112                           Lesotho
113                           Liberia
114                             Libya
115                     Liechtenstein
116                         Lithuania
117                        Luxembourg
118                             Macao
119                        Madagascar
120                            Malawi
121                          Malaysia
122                          Maldives
123                              Mali
124                             Malta
125                  Marshall Islands
126                        Mauritania
127                         Mauritius
128                            Mexico
129              Micronesia (country)
130                           Moldova
131                            Monaco
132                          Mongolia
133                        Montenegro
134                        Montserrat
135                           Morocco
136                        Mozambique
137                           Myanmar
138                           Namibia
139                             Nauru
140                             Nepal
141                       Netherlands
142                     New Caledonia
143                       New Zealand
144                         Nicaragua
145                             Niger
146                           Nigeria
147                              Niue
148                   North Macedonia
149                   Northern Cyprus
150                            Norway
151                              Oman
152                          Pakistan
153                             Palau
154                         Palestine
155                            Panama
156                  Papua New Guinea
157                          Paraguay
158                              Peru
159                       Philippines
160                          Pitcairn
161                            Poland
162                          Portugal
163                             Qatar
164                           Romania
165                            Russia
166                            Rwanda
167                      Saint Helena
168             Saint Kitts and Nevis
169                       Saint Lucia
170  Saint Vincent and the Grenadines
171                             Samoa
172                        San Marino
173             Sao Tome and Principe
174                      Saudi Arabia
175                           Senegal
176                            Serbia
177                        Seychelles
178                      Sierra Leone
179                         Singapore
180         Sint Maarten (Dutch part)
181                          Slovakia
182                          Slovenia
183                   Solomon Islands
184                           Somalia
185                      South Africa
186                       South Korea
187                       South Sudan
188                             Spain
189                         Sri Lanka
190                             Sudan
191                          Suriname
192                            Sweden
193                       Switzerland
194                             Syria
195                            Taiwan
196                        Tajikistan
197                          Tanzania
198                          Thailand
199                             Timor
200                              Togo
201                           Tokelau
202                             Tonga
203               Trinidad and Tobago
204                           Tunisia
205                            Turkey
206                      Turkmenistan
207          Turks and Caicos Islands
208                            Tuvalu
209                            Uganda
210                           Ukraine
211              United Arab Emirates
212                    United Kingdom
213                     United States
214                           Uruguay
215                        Uzbekistan
216                           Vanuatu
217                           Vatican
218                         Venezuela
219                           Vietnam
220                 Wallis and Futuna
221                             Yemen
222                            Zambia
223                          Zimbabwe

Now, we fix the column names of the dataframe

In [42]:
# Fix column names of the dataframe
fix_column_name(df_covid_vac)

df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

      location        date  total_cases  new_cases  total_deaths  new_deaths  \
0  Afghanistan  2020-02-24          5.0        5.0           NaN         NaN
1  Afghanistan  2020-02-25          5.0        0.0           NaN         NaN
2  Afghanistan  2020-02-26          5.0        0.0           NaN         NaN
3  Afghanistan  2020-02-27          5.0        0.0           NaN         NaN
4  Afghanistan  2020-02-28          5.0        0.0           NaN         NaN

   people_vaccinated  people_fully_vaccinated
0                NaN                      NaN
1                NaN                      NaN
2                NaN                      NaN
3                NaN                      NaN
4                NaN                      NaN

Then, we check if there are any missing values

In [43]:
# Find any missing values
find_total_missing_val_and_loc(df_covid_vac)

location                        0
date                            0
total_cases                  7393
new_cases                    7402
total_deaths                18384
new_deaths                  18388
people_vaccinated           97323
people_fully_vaccinated    100128
dtype: int64

,location,date,total_cases,new_cases,total_deaths,new_deaths,people_vaccinated,people_fully_vaccinated
0,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN
1,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN
2,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN
3,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN
4,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
134792,Zimbabwe,2021-08-26,123986.0,275.0,4356.0,18.0,NaN,NaN
134803,Zimbabwe,2021-09-06,125671.0,121.0,4493.0,11.0,NaN,NaN
134809,Zimbabwe,2021-09-12,126269.0,49.0,4538.0,2.0,NaN,NaN
134814,Zimbabwe,2021-09-17,127632.0,264.0,4562.0,2.0,NaN,NaN
134875,Zimbabwe,2021-11-17,133557.0,52.0,4699.0,1.0,NaN,NaN

For the `df_covid_vac` dataframe, we replace the `NaN` with the `0`

In [44]:
df_covid_vac.fillna(value=0, inplace=True)

In [45]:
# Check if any missing values still left
find_total_missing_val_and_loc(df_covid_vac)

No missing values

Finally, we normalise the country names

In [46]:
# Clean the country names
df_covid_vac = normalize_country_names(df_covid_vac, "location")

In [47]:
df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

      location        date  total_cases  new_cases  total_deaths  new_deaths  \
0  Afghanistan  2020-02-24          5.0        5.0           0.0         0.0
1  Afghanistan  2020-02-25          5.0        0.0           0.0         0.0
2  Afghanistan  2020-02-26          5.0        0.0           0.0         0.0
3  Afghanistan  2020-02-27          5.0        0.0           0.0         0.0
4  Afghanistan  2020-02-28          5.0        0.0           0.0         0.0

   people_vaccinated  people_fully_vaccinated
0                0.0                      0.0
1                0.0                      0.0
2                0.0                      0.0
3                0.0                      0.0
4                0.0                      0.0

#### VI. Basic cleaning of the `df_gdp` dataframe:

In [48]:
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

  GDP, current prices (Billions of U.S. dollars)     1980     1981     1982  \
0                                            NaN      NaN      NaN      NaN
1                                    Afghanistan  no data  no data  no data
2                                        Albania    1.946    2.229    2.296
3                                        Algeria   42.346   44.372    44.78
4                                        Andorra  no data  no data  no data

      1983     1984     1985     1986     1987     1988  ...     2017  \
0      NaN      NaN      NaN      NaN      NaN      NaN  ...      NaN
1  no data  no data  no data  no data  no data  no data  ...   18.883
2    2.319     2.29    2.339    2.587    2.566     2.53  ...   13.053
3   47.529   51.513   61.132   61.535     63.3   51.664  ...  170.207
4  no data  no data  no data  no data  no data  no data  ...    2.993

      2018    2019    2020     2021     2022     2023     2024     2025  \
0      NaN     NaN     NaN      NaN      NaN      NaN      NaN      NaN
1   18.401  18.876  20.136  no data  no data  no data  no data  no data
2   15.147  15.283  14.828    16.77   18.012   18.931   20.026    21.15
3  175.367  171.07   147.6  163.812  168.195  172.094  173.719  174.376
4    3.217   3.155   2.858    3.213     3.46    3.659    3.851    4.017

      2026
0      NaN
1  no data
2   22.308
3  175.228
4    4.179

[5 rows x 48 columns]

This dataframe has many columns. So lets see what are the column names in the table and keep only required columns

In [49]:
for i, c in enumerate(df_gdp.columns):
    print(i, c)

0 GDP, current prices (Billions of U.S. dollars)
1 1980
2 1981
3 1982
4 1983
5 1984
6 1985
7 1986
8 1987
9 1988
10 1989
11 1990
12 1991
13 1992
14 1993
15 1994
16 1995
17 1996
18 1997
19 1998
20 1999
21 2000
22 2001
23 2002
24 2003
25 2004
26 2005
27 2006
28 2007
29 2008
30 2009
31 2010
32 2011
33 2012
34 2013
35 2014
36 2015
37 2016
38 2017
39 2018
40 2019
41 2020
42 2021
43 2022
44 2023
45 2024
46 2025
47 2026

Rename the column: "GDP, current prices (Billions of U.S. dollars)".

In [50]:
df_gdp.rename(columns={"GDP, current prices (Billions of U.S. dollars)": "Country"}, inplace=True)

df_gdp.head(5)

,Country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,18.883,18.401,18.876,20.136,no data,no data,no data,no data,no data,no data
2,Albania,1.946,2.229,2.296,2.319,2.29,2.339,2.587,2.566,2.53,...,13.053,15.147,15.283,14.828,16.77,18.012,18.931,20.026,21.15,22.308
3,Algeria,42.346,44.372,44.78,47.529,51.513,61.132,61.535,63.3,51.664,...,170.207,175.367,171.07,147.6,163.812,168.195,172.094,173.719,174.376,175.228
4,Andorra,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,2.993,3.217,3.155,2.858,3.213,3.46,3.659,3.851,4.017,4.179

We only need following columns:
* 0 Country
* 33 2012
* 34 2013
* 35 2014
* 36 2015
* 37 2016
* 38 2017
* 39 2018
* 40 2019
* 41 2020
* 42 2021

In [51]:
df_gdp = df_gdp[["Country","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]]
df_gdp

,Country,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,20.293,20.17,20.616,20.057,18.02,18.883,18.401,18.876,20.136,no data
2,Albania,12.324,12.784,13.246,11.389,11.862,13.053,15.147,15.283,14.828,16.77
3,Algeria,209.059,209.755,213.81,165.979,160.034,170.207,175.367,171.07,147.6,163.812
4,Andorra,3.189,3.193,3.267,2.789,2.895,2.993,3.217,3.155,2.858,3.213
5,Angola,128.053,136.71,145.712,116.194,101.124,122.022,101.353,84.516,58.376,70.339
6,Antigua and Barbuda,1.2,1.181,1.25,1.337,1.437,1.468,1.605,1.687,1.37,1.405
7,Argentina,579.666,611.471,563.614,642.464,556.774,643.861,524.431,451.815,389.064,455.172
8,Armenia,10.619,11.121,11.61,10.553,10.546,11.527,12.458,13.619,12.641,13.612
9,Aruba,2.615,2.728,2.791,2.963,2.984,3.092,3.202,3.31,2.497,2.865
10,Australia,1569.311,1518.426,1457.381,1234.838,1266.196,1385.202,1421.194,1392.328,1359.372,1610.556
11,Austria,409.661,430.197,442.699,382.01,395.728,417.091,455.301,445.125,432.524,481.209
12,Azerbaijan,69.687,74.16,75.24,50.844,37.83,41.375,47.113,48.174,42.607,52.645
13,"Bahamas, The",10.72,10.495,11.143,11.891,11.993,12.36,12.838,13.164,9.908,10.681
14,Bahrain,30.749,32.539,33.388,31.051,32.235,35.474,37.652,38.467,34.729,39.104
15,Bangladesh,133.304,150.026,172.887,195.147,221.398,249.695,273.3,302.397,323.057,355.689
16,Barbados,4.61,4.677,4.696,4.715,4.83,4.978,5.087,5.298,4.418,4.648
17,Belarus,65.669,75.496,78.736,56.329,47.703,54.723,60.011,64.414,60.201,65.754
18,Belgium,496.467,521.799,535.529,462.383,475.931,502.587,543.923,533.313,514.92,581.848
19,Belize,1.523,1.579,1.667,1.722,1.789,1.859,1.916,1.983,1.706,1.909
20,Benin,11.148,12.518,13.288,11.389,11.818,12.697,14.257,14.392,15.674,18.067
21,Bhutan,1.772,1.805,1.784,1.922,2.025,2.365,2.411,2.488,2.503,2.48
22,Bolivia,27.282,30.883,33.237,33.241,34.189,37.782,40.581,41.193,36.839,38.547
23,Bosnia and Herzegovina,17.207,18.155,18.522,16.21,16.91,18.081,20.184,20.203,19.789,21.692
24,Botswana,15.519,14.368,15.663,13.602,15.094,16.068,16.914,16.592,15.064,17.605
25,Brazil,2464.054,2471.718,2456.055,1800.046,1796.622,2063.518,1916.934,1877.822,1444.718,1645.837
26,Brunei Darussalam,19.047,18.092,17.098,12.931,11.399,12.128,13.568,13.47,12.003,15.686
27,Bulgaria,54.031,55.617,56.902,50.647,53.802,59.093,66.294,68.563,69.209,77.907
28,Burkina Faso,12.569,13.444,13.947,11.833,12.83,14.102,16.067,15.991,17.378,19.932
29,Burundi,2.333,2.456,2.706,3.104,2.96,3.172,3.037,3.012,3.04,3.193
30,Cabo Verde,1.742,1.85,1.86,1.597,1.663,1.77,1.967,1.982,1.707,1.886
31,Cambodia,14.057,15.228,16.702,18.083,20.043,22.208,24.599,27.088,25.192,26.08
32,Cameroon,29.121,32.358,34.999,30.932,32.635,34.997,38.712,39.009,39.938,44.806
33,Canada,1828.362,1846.595,1805.751,1556.508,1527.996,1649.266,1721.822,1741.576,1644.037,2015.983
34,Central African Republic,2.512,1.692,1.896,1.696,1.825,2.072,2.28,2.277,2.387,2.587
35,Chad,12.411,12.994,14.003,10.952,10.202,10.079,11.036,10.934,10.836,12.345
36,Chile,267.021,278.347,260.473,243.89,250.332,276.929,297.501,279.338,252.821,331.25
37,"China, People's Republic of",8539.584,9624.928,10524.241,11113.508,11226.897,12265.327,13841.812,14340.6,14866.741,16862.979
38,Colombia,370.691,382.093,381.241,293.493,282.72,311.89,334.124,323.375,271.554,300.791
39,Comoros,1.016,1.116,1.15,0.966,1.013,1.077,1.179,1.188,1.216,1.281
40,"Congo, Dem. Rep. of the",29.35,32.695,35.911,37.915,36.64,37.981,47.146,50.399,48.707,54.832
41,"Congo, Republic of",17.704,17.959,17.918,11.891,10.159,11.11,13.649,12.791,10.329,12.744
42,Costa Rica,47.231,50.949,52.017,56.442,58.847,60.517,62.422,64.067,61.833,61.46
43,Croatia,56.581,58.194,57.64,49.526,51.601,55.482,61.375,60.752,56.171,63.399
44,Cyprus,24.993,23.9,23.162,19.844,20.947,22.721,25.322,24.953,23.785,26.546
45,Czech Republic,208.858,211.686,209.359,188.033,196.272,218.629,248.95,252.498,245.349,276.914
46,Cte d'Ivoire,37.03,43.228,48.882,45.815,47.964,51.588,58.011,58.539,61.231,68.845
47,Denmark,327.149,343.584,352.994,302.673,313.116,332.121,356.841,347.561,356.085,396.666
48,Djibouti,1.9,2.043,2.216,2.445,2.619,2.767,3.013,3.346,3.44,3.654
49,Dominica,0.486,0.498,0.52,0.541,0.576,0.54,0.564,0.616,0.544,0.571
50,Dominican Republic,60.747,62.758,67.264,71.254,75.777,80.082,85.63,89.032,78.923,89.502
51,Ecuador,87.925,95.13,101.726,99.29,99.938,104.296,107.562,108.108,98.808,104.483
52,Egypt,278.769,288.007,305.567,332.075,332.484,236.528,250.253,302.335,363.245,396.328
53,El Salvador,21.386,21.991,22.593,23.438,24.191,24.979,26.021,26.897,24.639,27.665
54,Equatorial Guinea,22.388,21.949,21.765,13.185,11.241,12.201,13.097,11.417,10.036,12.528
55,Eritrea,2.255,1.958,2.604,2.016,2.213,1.904,2.006,1.982,2.084,2.254
56,Estonia,23.034,25.116,26.641,22.893,24.066,26.915,30.503,31.049,30.626,36.039
57,Eswatini,4.887,4.6,4.426,4.061,3.815,4.407,4.666,4.471,3.981,4.517
58,Ethiopia,42.221,46.544,54.165,63.081,72.12,76.841,80.207,92.608,96.611,92.757
59,Fiji,4.303,4.539,4.857,4.682,4.93,5.353,5.581,5.496,4.494,4.639
60,Finland,258.454,271.366,274.934,234.558,240.705,255.558,275.84,268.812,269.557,296.016
61,France,2683.893,2811.04,2852.171,2438.208,2471.261,2589.031,2789.68,2728.834,2624.416,2940.428
62,Gabon,17.181,17.596,18.209,14.385,14.02,14.924,16.875,16.875,15.339,18.293
63,"Gambia, The",1.415,1.376,1.229,1.355,1.47,1.498,1.662,1.806,1.862,2.042
64,Georgia,16.489,17.19,17.627,14.953,15.141,16.242,17.599,17.477,15.891,17.846
65,Germany,3529.377,3733.859,3890.095,3357.926,3468.896,3689.547,3979.093,3888.756,3843.335,4230.172
66,Ghana,56.853,63.703,54.285,49.437,56.144,60.385,67.259,68.353,68.498,75.487
67,Greece,242.193,238.555,235.669,195.416,192.81,200.055,212.346,205.349,189.259,211.645
68,Grenada,0.8,0.843,0.911,0.997,1.062,1.126,1.167,1.188,1.027,1.083
69,Guatemala,49.902,52.989,57.835,62.18,66.034,71.624,73.212,77.004,77.603,83.305
70,Guinea,7.304,8.374,8.777,8.79,8.604,10.325,11.857,13.514,15.388,16.724
71,Guinea-Bissau,1.05,1.11,1.136,1.153,1.245,1.469,1.506,1.44,1.434,1.592
72,Guyana,4.063,4.168,4.128,4.28,4.483,4.748,4.788,5.174,5.471,7.395
73,Haiti,13.709,14.904,15.137,14.831,13.996,15.036,16.454,14.787,14.508,20.143
74,Honduras,18.529,18.5,19.757,20.98,21.718,23.136,24.068,25.09,23.828,26.325
75,Hong Kong SAR,262.629,275.697,291.46,309.386,320.84,341.242,361.692,363.016,346.584,369.722
76,Hungary,128.475,135.412,140.765,125.074,128.471,142.962,160.431,163.494,155.013,180.959
77,Iceland,14.752,16.125,17.868,17.517,20.793,24.728,26.267,24.858,21.718,25.476
78,India,1827.637,1856.721,2039.127,2103.588,2294.118,2651.474,2701.112,2870.504,2660.244,2946.061
79,Indonesia,919.002,916.646,891.051,860.741,932.066,1015.488,1042.711,1120.042,1059.638,1150.245
80,Iran,392.295,400.087,433.088,385.023,418.064,445.528,456.59,581.252,835.351,1081.383
81,Iraq,218.032,234.638,234.651,177.634,167.716,192.343,226.87,233.953,169.488,201.472
82,Ireland,225.64,238.282,259.037,291.611,298.846,335.312,385.215,399.165,425.549,516.253
83,Israel,258.417,294.167,310.945,300.078,319.025,355.277,373.641,397.935,407.101,467.532
84,Italy,2088.278,2141.954,2162.567,1836.824,1876.554,1961.104,2093.088,2005.135,1884.935,2120.232
85,Jamaica,14.765,14.213,13.865,14.154,14.108,14.755,15.648,15.808,13.967,14.857
86,Japan,6272.364,5212.328,4896.995,4444.931,5003.678,4930.837,5036.892,5135.896,5045.101,5103.11
87,Jordan,31.679,34.503,36.9,38.642,39.949,41.467,42.993,44.566,43.759,45.344
88,Kazakhstan,207.999,236.635,221.416,184.388,137.289,166.806,179.34,181.667,171.24,194.024
89,Kenya,56.407,61.703,68.395,70.369,74.817,81.964,92.227,100.458,102.427,109.491
90,Kiribati,0.19,0.186,0.18,0.171,0.178,0.187,0.2,0.198,0.198,0.232
91,"Korea, Republic of",1278.046,1370.633,1484.489,1466.039,1499.362,1623.074,1725.373,1651.423,1638.258,1823.852
92,Kosovo,6.504,7.074,7.398,6.444,6.717,7.243,7.947,7.953,7.78,8.958
93,Kuwait,174.066,174.179,162.695,114.606,109.381,120.687,138.202,136.192,105.949,132.266
94,Kyrgyz Republic,6.604,7.335,7.467,6.678,6.813,7.703,8.271,8.872,7.747,8.15
95,Lao P.D.R.,10.195,11.974,13.266,14.363,15.905,17.055,18.131,18.771,18.82,19.375
96,Latvia,28.346,30.442,31.379,27.253,28.064,30.448,34.432,34.059,33.478,37.199
97,Lebanon,44.036,46.909,48.133,50.066,51.389,53.325,55.276,52.371,19.008,no data
98,Lesotho,2.465,2.345,2.477,2.207,2.219,2.356,2.32,2.228,1.999,2.478
99,Liberia,2.675,3.044,3.09,3.092,3.256,3.321,3.264,3.08,3.037,3.384
100,Libya,79.759,51.896,24.262,17.216,18.563,30.211,41.432,39.497,19.21,27.3
101,Lithuania,42.952,46.537,48.611,41.44,43.035,47.742,53.747,54.646,55.843,62.635
102,Luxembourg,56.711,61.758,66.209,57.773,60.716,64.159,70.952,71.113,73.205,83.771
103,Macao SAR,43.19,51.536,54.903,45.06,45.085,50.457,55.303,55.154,24.333,29.223
104,Madagascar,11.579,12.424,12.523,11.323,11.849,13.176,13.76,14.105,13.179,14.101
105,Malawi,8.421,7.648,8.526,9.014,7.733,8.943,9.882,11.031,11.847,12.15
106,Malaysia,318.91,327.869,342.868,301.355,301.255,319.109,358.789,365.279,337.008,371.114
107,Maldives,2.885,3.286,3.69,4.098,4.367,4.747,5.293,5.632,3.738,4.573
108,Mali,12.45,13.243,14.369,13.106,14.022,15.36,17.079,17.281,17.491,19.563
109,Malta,9.468,10.551,11.629,11.093,11.693,13.506,15.335,15.728,14.899,16.695
110,Marshall Islands,0.181,0.185,0.182,0.184,0.201,0.212,0.222,0.236,0.244,0.241
111,Mauritania,6.721,7.331,6.615,6.182,6.414,6.826,7.351,7.889,8.11,9.164
112,Mauritius,11.669,12.13,12.803,11.692,12.232,13.259,14.182,14.046,10.921,10.998
113,Mexico,1201.094,1274.444,1315.356,1171.87,1078.493,1158.912,1222.406,1269.432,1073.915,1285.518
114,"Micronesia, Fed. States of",0.327,0.317,0.319,0.316,0.332,0.367,0.402,0.413,0.407,0.404
115,Moldova,8.708,9.496,9.51,7.726,8.072,9.67,11.457,11.972,11.912,12.396
116,Mongolia,12.278,12.582,12.227,11.75,11.159,11.426,13.138,13.997,13.137,14.28
117,Montenegro,4.09,4.466,4.595,4.055,4.376,4.855,5.509,5.543,4.786,5.494
118,Morocco,98.266,106.826,110.081,101.179,103.312,109.683,118.096,119.871,114.602,126.035
119,Mozambique,16.351,16.974,17.716,15.951,11.937,13.219,14.845,15.39,14.029,15.833
120,Myanmar,59,60.903,63.153,62.655,60.09,61.267,66.699,68.802,81.257,66.74
121,Namibia,13.016,12.168,12.434,11.45,10.719,12.883,13.675,12.563,10.71,12.213
122,Nauru,0.097,0.099,0.105,0.087,0.1,0.11,0.124,0.119,0.114,0.133
123,Nepal,21.703,22.161,22.722,24.361,24.524,28.972,33.112,34.186,33.983,34.265
124,Netherlands,839.455,877.186,892.398,765.65,783.844,833.575,914.458,910.295,913.134,1007.562
125,New Zealand,175.032,187.168,200.142,176.213,185.956,203.842,210.005,210.443,209.384,247.64
126,Nicaragua,10.532,10.983,11.88,12.757,13.286,13.786,13.025,12.625,12.62,13.397
127,Niger,9.412,10.206,10.83,9.684,10.35,11.185,12.85,12.912,13.761,15.637
128,Nigeria,460.952,514.966,568.499,492.437,404.649,375.745,421.737,448.12,429.423,480.482
129,North Macedonia,9.751,10.824,11.378,10.067,10.686,11.336,12.694,12.55,12.288,13.885
130,Norway,509.506,522.762,498.41,385.802,368.827,398.394,437,405.51,362.522,445.507
131,Oman,76.616,78.784,81.077,68.919,65.481,70.598,79.789,76.332,63.368,80.611
132,Pakistan,223.119,230.644,243.94,270.17,278.023,304.603,313.073,276.942,261.726,no data
133,Palau,0.212,0.224,0.243,0.29,0.3,0.287,0.286,0.275,0.257,0.208
134,Panama,40.43,45.6,49.921,54.092,57.908,62.203,64.928,66.788,52.938,60.121
135,Papua New Guinea,21.295,21.261,23.211,21.723,20.759,22.743,24.11,24.829,23.279,26.461
136,Paraguay,33.296,38.651,40.378,36.211,36.09,38.997,40.225,37.907,35.67,36.973
137,Peru,192.85,202.082,202.278,191.247,194.266,214.128,225.369,230.865,205.458,225.858
138,Philippines,261.92,283.903,297.484,306.446,318.627,328.481,346.842,376.823,361.489,385.737
139,Poland,498.517,521.013,542.602,477.488,472.256,526.643,587.433,597.194,595.916,655.332
140,Portugal,216.361,226.437,229.961,199.414,206.369,221.28,242.423,240.013,228.356,251.709
141,Puerto Rico,101.565,102.45,102.446,103.376,104.337,103.446,104.925,104.915,103.138,106.576
142,Qatar,186.834,198.728,206.225,161.74,151.732,161.099,183.335,175.838,145.45,169.184
143,Romania,170.636,190.8,199.961,177.731,188.13,211.696,241.456,249.695,248.716,287.279
144,Russian Federation,2191.484,2288.428,2048.836,1356.704,1280.648,1575.14,1653.005,1690.05,1478.571,1647.568
145,Rwanda,7.651,7.816,8.234,8.542,8.691,9.253,9.641,10.356,10.332,10.395
146,Saint Kitts and Nevis,0.826,0.875,0.954,0.958,1.009,1.061,1.079,1.165,0.981,0.976
147,Saint Lucia,1.606,1.666,1.756,1.81,1.866,1.997,2.065,2.119,1.617,1.715
148,Saint Vincent and the Grenadines,0.693,0.721,0.728,0.755,0.774,0.792,0.811,0.825,0.807,0.769
149,Samoa,0.759,0.764,0.757,0.788,0.799,0.832,0.837,0.846,0.812,0.78
150,San Marino,1.606,1.678,1.674,1.42,1.468,1.528,1.656,1.616,1.554,1.728
151,Saudi Arabia,735.975,746.647,756.35,654.27,644.935,688.586,786.522,792.966,700.118,842.588
152,Senegal,17.672,18.919,19.802,17.777,19.035,20.989,23.127,23.307,24.681,27.576
153,Serbia,43.33,48.428,47.095,39.656,40.693,44.179,50.641,51.475,52.96,60.669
154,Seychelles,1.06,1.328,1.343,1.377,1.426,1.528,1.542,1.58,1.138,1.288
155,Sierra Leone,3.802,4.916,5.007,4.252,3.855,3.713,4.085,4.119,4.202,4.407
156,Singapore,295.093,307.576,314.864,307.999,318.753,343.332,375.963,374.39,339.981,378.645
157,Slovak Republic,94.589,98.878,101.351,88.512,89.691,95.411,105.574,105.131,104.491,116.748
158,Slovenia,46.607,48.416,50.01,43.112,44.754,48.572,54.188,54.185,53.547,60.89
159,Solomon Islands,1.191,1.285,1.338,1.311,1.381,1.458,1.566,1.579,1.562,1.649
160,Somalia,3.611,3.892,3.964,4.049,4.198,4.509,4.651,5.061,4.99,5.424
161,South Africa,434.4,400.877,381.195,346.663,323.493,381.317,404.673,387.849,335.344,415.315
162,"South Sudan, Republic of",11.267,14.947,15.383,14.801,3.501,3.495,4.659,4.589,4.44,3.263
163,Spain,1325.583,1355.162,1371.576,1195.721,1232.573,1312.076,1421.639,1393.2,1280.459,1439.958
164,Sri Lanka,68.381,74.253,79.312,80.557,82.39,87.422,87.922,83.978,80.7,80.785
165,Sudan,48.948,52.892,60.726,64.536,64.883,47.837,33.432,33.564,34.396,35.919
166,Suriname,5.332,5.51,5.612,5.126,3.317,3.592,3.996,3.984,2.884,2.817
167,Sweden,552.484,586.842,581.964,505.104,515.655,541.019,555.455,533.88,541.064,622.365
168,Switzerland,692.382,713.232,734.703,702.195,695.434,704.758,736.089,732.492,751.877,810.83
169,Syria,no data,no data,no data,no data,no data,no data,no data,no data,no data,no data
170,So Tom and Prncipe,0.253,0.303,0.349,0.318,0.348,0.376,0.416,0.431,0.477,0.534
171,Taiwan Province of China,495.61,512.943,535.328,534.515,543.081,590.733,609.198,612.168,668.156,785.589
172,Tajikistan,7.592,8.506,9.242,7.857,6.953,7.144,7.52,8.117,7.997,8.104
173,Tanzania,39.651,45.681,50.002,47.384,49.774,53.227,56.699,60.81,64.403,69.238
174,Thailand,397.722,420.364,407.373,401.142,413.497,456.523,506.403,544.21,501.712,546.223
175,Timor-Leste,1.148,1.396,1.447,1.594,1.651,1.599,1.56,2.018,1.777,1.697
176,Togo,5.229,5.831,6.174,5.641,6.03,6.393,7.115,7.221,7.586,8.493
177,Tonga,0.471,0.451,0.44,0.437,0.421,0.46,0.486,0.517,0.499,0.501
178,Trinidad and Tobago,25.763,27.268,27.616,24.96,22.394,22.385,23.68,23.208,21.587,21.599
179,Tunisia,45.044,46.248,47.634,43.172,41.801,39.627,40.139,39.169,39.219,42.733
180,Turkey,880.141,957.504,938.512,864.071,869.28,858.932,779.694,760.516,719.919,795.952
181,Turkmenistan,51.756,53.124,57.897,42.162,38.502,41.385,40.762,46.264,45.609,53.087
182,Tuvalu,0.039,0.039,0.039,0.037,0.041,0.045,0.048,0.054,0.055,0.065
183,Uganda,30.939,32.331,33.122,27.445,29.598,31.398,34.223,38.001,38.141,43.243
184,Ukraine,175.707,179.574,130.571,90.477,93.313,112.114,130.916,153.997,155.3,181.038
185,United Arab Emirates,374.591,390.108,403.137,358.135,357.045,385.605,422.215,417.216,358.869,410.158
186,United Kingdom,2704.498,2785.062,3067.117,2933.433,2703.242,2664.705,2860.982,2833.301,2709.678,3108.416
187,United States,16253.95,16843.225,17550.675,18206.025,18695.1,19479.625,20527.15,21372.6,20893.75,22939.58
188,Uruguay,55.692,62.499,62.178,57.874,57.237,64.234,64.766,61.931,56.577,60.108
189,Uzbekistan,67.52,73.192,80.848,85.662,85.658,61.018,52.618,59.907,59.928,65.503
190,Vanuatu,0.736,0.755,0.774,0.744,0.775,0.88,0.928,0.928,0.932,0.999
191,Venezuela,352.191,258.993,203.822,323.595,279.249,143.841,98.4,63.96,47.255,44.893
192,Vietnam,195.169,212.728,232.888,236.795,252.146,277.071,303.091,327.873,343.114,368.002
193,West Bank and Gaza,12.208,13.516,13.99,13.972,15.405,16.128,16.277,17.134,15.561,17.343
194,Yemen,35.401,40.415,43.229,42.444,31.318,26.842,21.606,21.888,18.841,19.471
195,Zambia,25.502,28.042,27.145,21.245,20.965,25.874,26.312,23.309,19.319,21.699
196,Zimbabwe,17.115,19.091,19.496,19.963,20.549,22.041,23.516,19.587,21.924,25.791
197,Africa (Region),2424.463,2502.527,2584.357,2353.868,2237.952,2257.39,2405.657,2473.202,2391.75,2687.173
198,Asia and Pacific,24742.562,25118.456,26035.948,25812.208,26864.722,28798.15,30891.366,31732.644,31730.164,35134.628
199,Australia and New Zealand,1744.343,1705.594,1657.523,1411.051,1452.152,1589.043,1631.199,1602.771,1568.756,1858.196
200,Caribbean,88.712,91.327,92.774,91.04,86.617,89.788,94.899,94.316,83.293,93.434
201,Central America,248.756,263.77,281.268,301.142,317.761,336.327,349.305,361.503,332.384,361.775
202,Central Asia and the Caucasus,1338.7,1458.937,1440.475,1287.226,1226.033,1231.016,1163.776,1163.489,1103.715,1229.249
203,East Asia,16860.511,17009.111,17744.739,17880.128,18605.016,19762.639,21588.103,22117.099,22577.976,24959.532
204,Eastern Europe,3880.897,4069.763,3827.71,2884.322,2834.405,3306.744,3603.949,3696.753,3458.992,3880.569
205,Europe,21092.996,21984.286,22333.343,19183.684,19192.708,20394.592,22006.071,21708.916,20924.682,23498.813
206,Middle East (Region),2570.9,2685.221,2763.807,2396.58,2403.675,2592.959,2840.969,2986.108,2917.591,3523.065
207,North Africa,710.897,702.732,701.354,659.621,656.193,586.256,625.288,671.942,683.876,756.208
208,North America,19384.971,20066.714,20774.228,21037.779,21405.926,22391.249,23576.303,24488.523,23714.841,26347.657
209,Pacific Islands,28.945,29.24,31.556,29.858,29.243,31.914,33.709,34.392,31.776,35.262
210,South America,4430.669,4431.866,4305.002,3721.353,3587.415,3899.477,3649.894,3476.315,2838.765,3243.911
211,South Asia,2278.801,2338.896,2563.461,2679.842,2906.845,3329.277,3416.224,3576.127,3365.952,3722.847
212,Southeast Asia,2491.262,2576.677,2598.194,2524.104,2645.432,2854.26,3058.355,3238.766,3081.99,3329.543
213,Sub-Saharan Africa (Region),1713.566,1799.795,1883.003,1694.247,1581.759,1671.134,1780.369,1801.26,1707.874,1930.965
214,Western Europe,17212.099,17914.523,18505.633,16299.363,16358.303,17087.848,18402.122,18012.163,17465.69,19618.245
215,Western Hemisphere (Region),24153.108,24853.677,25453.271,25151.313,25397.72,26716.841,27670.402,28420.657,26969.283,30046.777
216,ASEAN-5,2092.723,2161.509,2171.664,2106.479,2217.592,2396.672,2557.836,2734.227,2602.96,2821.32
217,Advanced economies,46490.054,46898.344,47978.361,45395.572,46613.594,48611.898,51452.674,51955.575,50668.216,56086.679
218,Emerging and Developing Asia,12833.515,14044.967,15171.763,15781.806,16223.775,17845.289,19675.283,20553.645,20758.965,23288.324
219,Emerging and Developing Europe,4323.155,4573.266,4306.27,3343.594,3284.519,3705.202,3864.195,3933.654,3663.358,4095.052
220,Emerging market and developing economies,28548.136,30309.19,31259.517,29558.55,29540.159,32211.263,34430.774,35435.216,34303.433,38848.435
221,Euro area,12643.759,13192.377,13510.156,11672.868,11967.505,12671.894,13706.763,13409.167,13000.592,14518.469
222,European Union,14638.793,15294.584,15647.815,13547.917,13885.786,14754.334,15981.295,15682.496,15263.841,17078.376
223,Latin America and the Caribbean,5969.231,6061.407,5994.399,5285.405,5070.287,5484.504,5316.504,5201.565,4328.358,4984.638
224,Major advanced economies (G7),35360.723,35374.063,36225.372,34773.854,35746.727,36964.115,39008.707,39706.099,38645.253,42457.921
225,Middle East and Central Asia,3766.238,3892.021,3973.639,3526.661,3453.734,3562.562,3838.219,3989.89,3890.824,4598.192

Now, we fix the column names of the dataframe

In [52]:
# Fix column names of the dataframe
fix_column_name(df_gdp)

df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013    2014     2015     2016     2017     2018  \
0          NaN      NaN      NaN     NaN      NaN      NaN      NaN      NaN
1  Afghanistan   20.293    20.17  20.616   20.057    18.02   18.883   18.401
2      Albania   12.324   12.784  13.246   11.389   11.862   13.053   15.147
3      Algeria  209.059  209.755  213.81  165.979  160.034  170.207  175.367
4      Andorra    3.189    3.193   3.267    2.789    2.895    2.993    3.217

     2019    2020     2021
0     NaN     NaN      NaN
1  18.876  20.136  no data
2  15.283  14.828    16.77
3  171.07   147.6  163.812
4   3.155   2.858    3.213

Then, we check if there are any missing values

In [53]:
find_total_missing_val_and_loc(df_gdp)

Country    2
2012       3
2013       3
2014       3
2015       3
2016       3
2017       3
2018       3
2019       3
2020       3
2021       3
dtype: int64

        Country 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
0           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
229         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
230  ©IMF, 2021  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

We remove rows with indices 0, 229 and 230 as they junk rows with no country name and gdp value.

In [54]:
df_gdp.drop([0,229,230], axis=0, inplace=True)

We also remove the rows with indices in the range[197, 228] as these rows do not correspond to any country but rather to various regions of the world.

In [55]:
df_gdp.drop(df_gdp.index[197:228], axis=0, inplace=True)

We also observe that some records are marked as _'no data'_.

We replace these records with 0

In [56]:
df_gdp.replace(['no data'], [0], inplace=True)

In [57]:
df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013     2014     2015     2016     2017     2018  \
1  Afghanistan   20.293    20.17   20.616   20.057    18.02   18.883   18.401
2      Albania   12.324   12.784   13.246   11.389   11.862   13.053   15.147
3      Algeria  209.059  209.755   213.81  165.979  160.034  170.207  175.367
4      Andorra    3.189    3.193    3.267    2.789    2.895    2.993    3.217
5       Angola  128.053   136.71  145.712  116.194  101.124  122.022  101.353

     2019    2020     2021
1  18.876  20.136        0
2  15.283  14.828    16.77
3  171.07   147.6  163.812
4   3.155   2.858    3.213
5  84.516  58.376   70.339

In [58]:
find_total_missing_val_and_loc(df_gdp)

No missing values

Finally, we normalise the country names

In [59]:
# Clean the country names
df_gdp = normalize_country_names(df_gdp, "Country")

In [60]:
df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013     2014     2015     2016     2017     2018  \
1  Afghanistan   20.293    20.17   20.616   20.057    18.02   18.883   18.401
2      Albania   12.324   12.784   13.246   11.389   11.862   13.053   15.147
3      Algeria  209.059  209.755   213.81  165.979  160.034  170.207  175.367
4      Andorra    3.189    3.193    3.267    2.789    2.895    2.993    3.217
5       Angola  128.053   136.71  145.712  116.194  101.124  122.022  101.353

     2019    2020     2021
1  18.876  20.136        0
2  15.283  14.828    16.77
3  171.07   147.6  163.812
4   3.155   2.858    3.213
5  84.516  58.376   70.339

---

### Part II - Matching country names of all dataframes to that of the `df_population` dataframe

Now we proceed to the second part of the data pre-processing section, where we match and normalise the country name of all the dataframes with reference to the country names in the `df_population` dataframe.

We define the below functions to match and normalise the country names.

In [61]:
# Define function to first save each DF's index and work with the unmatching records only.

def filter_unmatched_index(df_primary, df_ancillary, col_primary, col_ancillary):
    """
    This function returns the non-matching entries on columns
    given with indexes in columns 'primary' and 'ancillary'
    
    This function also saves each DF's index as 'index_primary'
    and 'index_ancillary', and return the records which are not
    matching between the two columns.
    """
    df_p = df_primary[[col_primary]]
    df_p.index.name = 'index_primary'
    df_p.reset_index(inplace=True)
    
    df_a = df_ancillary[[col_ancillary]]
    df_a.index.name = 'index_ancillary'
    df_a.reset_index(inplace=True)
    
    df_outer = pd.merge(df_p, df_a, left_on=col_primary, right_on=col_ancillary, how="outer")
    index_nulls = find_total_missing_val_and_loc(df_outer)
    
    return index_nulls

In [62]:
# Define the function to check for similarities between country names with 'difflib'.

def get_close_matches(name, list_compare, pad=True):
    
    """
    This function returns the best matching entry
    from 'list_compare' to 'name'
    
    Input:
        name: string
        list_compare: [string]
        
    """
    from difflib import get_close_matches
    match_list = get_close_matches(name, list_compare, n=1, cutoff=0.5)
    
    if len(match_list):
        return match_list[0]
    else:
        return name if pad else None

In [63]:
# Define a function to add columns: best-matched and no-match for country names

def find_divergence(df, col_name):
    """
    This function adds "CnT-pad" and "CnT-noPad" and
    returns the records with non-matching country names
    of df with df_population.
    
    Input:
        df: Pandas DataFrame
        col_name: string
    
    Return:
        Pandas DataFrame

    """
    df_2 = df.copy()

    # merge tables
    df_merge_unmatch = filter_unmatched_index(df_population, df_2,"name", col_name)

    # Define the country name in "df_2" as the primary series
    # Then modify with the values from "Population-2020-21" table
    primary = df_merge_unmatch[col_name].dropna()
    options = df_merge_unmatch["name"].dropna()

    # Add column 'CnT-pad' to "df_merge_unmatch" with either the best match from options (if any)
    # or the primary/self (if there is no good match)
    df_merge_unmatch["CnT-pad"] = primary.apply(lambda country: get_close_matches(country, options))

    # Add column 'CnT-noPad' to "df_merge_unmatch" which has None when there is no good match
    df_merge_unmatch["CnT-noPad"] = primary.apply(lambda country: get_close_matches(country, options, pad=False))

    return df_merge_unmatch[["index_primary", "name", "index_ancillary", col_name,"CnT-pad","CnT-noPad"]]

#### I. Match country names in `df_tokyo`:

In [64]:
df_tmp = find_divergence(df_tokyo, df_tokyo.columns[0])

df_tmp

index_primary       12
name                12
index_ancillary    151
Country            151
dtype: int64

,index_primary,name,index_ancillary,Country,CnT-pad,CnT-noPad
0,0.0,Afghanistan,NaN,NaN,NaN,NaN
1,1.0,Albania,NaN,NaN,NaN,NaN
2,2.0,Algeria,NaN,NaN,NaN,NaN
3,3.0,American Samoa,NaN,NaN,NaN,NaN
4,4.0,Andorra,NaN,NaN,NaN,NaN
5,5.0,Angola,NaN,NaN,NaN,NaN
6,6.0,Anguilla,NaN,NaN,NaN,NaN
7,7.0,Antigua and Barbuda,NaN,NaN,NaN,NaN
10,10.0,Aruba,NaN,NaN,NaN,NaN
16,16.0,Bangladesh,NaN,NaN,NaN,NaN
17,17.0,Barbados,NaN,NaN,NaN,NaN
20,20.0,Belize,NaN,NaN,NaN,NaN
21,21.0,Benin,NaN,NaN,NaN,NaN
23,23.0,Bhutan,NaN,NaN,NaN,NaN
24,24.0,Bolivia,NaN,NaN,NaN,NaN
25,25.0,Bosnia and Herzegovina,NaN,NaN,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN,NaN,NaN
29,29.0,Brunei,NaN,NaN,NaN,NaN
32,32.0,Burundi,NaN,NaN,NaN,NaN
33,33.0,Cambodia,NaN,NaN,NaN,NaN
34,34.0,Cameroon,NaN,NaN,NaN,NaN
36,36.0,Cape Verde,NaN,NaN,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN,NaN,NaN
38,38.0,Central African Republic,NaN,NaN,NaN,NaN
39,39.0,Chad,NaN,NaN,NaN,NaN
40,40.0,Chile,NaN,NaN,NaN,NaN
41,41.0,China,NaN,NaN,NaN,NaN
43,43.0,Comoros,NaN,NaN,NaN,NaN
44,44.0,Cook Islands,NaN,NaN,NaN,NaN
45,45.0,Costa Rica,NaN,NaN,NaN,NaN
48,48.0,Curacao,NaN,NaN,NaN,NaN
49,49.0,Cyprus,NaN,NaN,NaN,NaN
52,52.0,Djibouti,NaN,NaN,NaN,NaN
53,53.0,Dominica,NaN,NaN,NaN,NaN
55,55.0,DR Congo,NaN,NaN,NaN,NaN
58,58.0,El Salvador,NaN,NaN,NaN,NaN
59,59.0,Equatorial Guinea,NaN,NaN,NaN,NaN
60,60.0,Eritrea,NaN,NaN,NaN,NaN
62,62.0,Eswatini,NaN,NaN,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN,NaN,NaN
69,69.0,French Guiana,NaN,NaN,NaN,NaN
70,70.0,French Polynesia,NaN,NaN,NaN,NaN
71,71.0,Gabon,NaN,NaN,NaN,NaN
72,72.0,Gambia,NaN,NaN,NaN,NaN
76,76.0,Gibraltar,NaN,NaN,NaN,NaN
78,78.0,Greenland,NaN,NaN,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN,NaN,NaN
81,81.0,Guam,NaN,NaN,NaN,NaN
82,82.0,Guatemala,NaN,NaN,NaN,NaN
83,83.0,Guinea,NaN,NaN,NaN,NaN
84,84.0,Guinea-Bissau,NaN,NaN,NaN,NaN
85,85.0,Guyana,NaN,NaN,NaN,NaN
86,86.0,Haiti,NaN,NaN,NaN,NaN
87,87.0,Honduras,NaN,NaN,NaN,NaN
88,88.0,Hong Kong,NaN,NaN,NaN,NaN
90,90.0,Iceland,NaN,NaN,NaN,NaN
93,93.0,Iran,NaN,NaN,NaN,NaN
94,94.0,Iraq,NaN,NaN,NaN,NaN
96,96.0,Isle of Man,NaN,NaN,NaN,NaN
99,99.0,Ivory Coast,NaN,NaN,NaN,NaN
105,105.0,Kiribati,NaN,NaN,NaN,NaN
108,108.0,Laos,NaN,NaN,NaN,NaN
110,110.0,Lebanon,NaN,NaN,NaN,NaN
111,111.0,Lesotho,NaN,NaN,NaN,NaN
112,112.0,Liberia,NaN,NaN,NaN,NaN
113,113.0,Libya,NaN,NaN,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN,NaN,NaN
116,116.0,Luxembourg,NaN,NaN,NaN,NaN
117,117.0,Macau,NaN,NaN,NaN,NaN
118,118.0,Madagascar,NaN,NaN,NaN,NaN
119,119.0,Malawi,NaN,NaN,NaN,NaN
121,121.0,Maldives,NaN,NaN,NaN,NaN
122,122.0,Mali,NaN,NaN,NaN,NaN
123,123.0,Malta,NaN,NaN,NaN,NaN
124,124.0,Marshall Islands,NaN,NaN,NaN,NaN
125,125.0,Martinique,NaN,NaN,NaN,NaN
126,126.0,Mauritania,NaN,NaN,NaN,NaN
127,127.0,Mauritius,NaN,NaN,NaN,NaN
128,128.0,Mayotte,NaN,NaN,NaN,NaN
130,130.0,Micronesia,NaN,NaN,NaN,NaN
131,131.0,Moldova,NaN,NaN,NaN,NaN
132,132.0,Monaco,NaN,NaN,NaN,NaN
134,134.0,Montenegro,NaN,NaN,NaN,NaN
135,135.0,Montserrat,NaN,NaN,NaN,NaN
137,137.0,Mozambique,NaN,NaN,NaN,NaN
138,138.0,Myanmar,NaN,NaN,NaN,NaN
140,140.0,Nauru,NaN,NaN,NaN,NaN
141,141.0,Nepal,NaN,NaN,NaN,NaN
143,143.0,New Caledonia,NaN,NaN,NaN,NaN
145,145.0,Nicaragua,NaN,NaN,NaN,NaN
146,146.0,Niger,NaN,NaN,NaN,NaN
148,148.0,Niue,NaN,NaN,NaN,NaN
149,149.0,North Korea,NaN,NaN,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN,NaN,NaN
153,153.0,Oman,NaN,NaN,NaN,NaN
154,154.0,Pakistan,NaN,NaN,NaN,NaN
155,155.0,Palau,NaN,NaN,NaN,NaN
156,156.0,Palestine,NaN,NaN,NaN,NaN
157,157.0,Panama,NaN,NaN,NaN,NaN
158,158.0,Papua New Guinea,NaN,NaN,NaN,NaN
159,159.0,Paraguay,NaN,NaN,NaN,NaN
160,160.0,Peru,NaN,NaN,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN,NaN,NaN
167,167.0,Reunion,NaN,NaN,NaN,NaN
169,169.0,Russia,NaN,NaN,NaN,NaN
170,170.0,Rwanda,NaN,NaN,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN,NaN,NaN
172,172.0,Saint Kitts and Nevis,NaN,NaN,NaN,NaN
173,173.0,Saint Lucia,NaN,NaN,NaN,NaN
174,174.0,Saint Martin,NaN,NaN,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN
176,176.0,Saint Vincent and the Grenadines,NaN,NaN,NaN,NaN
177,177.0,Samoa,NaN,NaN,NaN,NaN
179,179.0,Sao Tome and Principe,NaN,NaN,NaN,NaN
181,181.0,Senegal,NaN,NaN,NaN,NaN
183,183.0,Seychelles,NaN,NaN,NaN,NaN
184,184.0,Sierra Leone,NaN,NaN,NaN,NaN
185,185.0,Singapore,NaN,NaN,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN,NaN,NaN
189,189.0,Solomon Islands,NaN,NaN,NaN,NaN
190,190.0,Somalia,NaN,NaN,NaN,NaN
192,192.0,South Korea,NaN,NaN,NaN,NaN
193,193.0,South Sudan,NaN,NaN,NaN,NaN
195,195.0,Sri Lanka,NaN,NaN,NaN,NaN
196,196.0,Sudan,NaN,NaN,NaN,NaN
197,197.0,Suriname,NaN,NaN,NaN,NaN
200,200.0,Syria,NaN,NaN,NaN,NaN
201,201.0,Taiwan,NaN,NaN,NaN,NaN
202,202.0,Tajikistan,NaN,NaN,NaN,NaN
203,203.0,Tanzania,NaN,NaN,NaN,NaN
205,205.0,Timor-Leste,NaN,NaN,NaN,NaN
206,206.0,Togo,NaN,NaN,NaN,NaN
207,207.0,Tokelau,NaN,NaN,NaN,NaN
208,208.0,Tonga,NaN,NaN,NaN,NaN
209,209.0,Trinidad and Tobago,NaN,NaN,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN,NaN,NaN
214,214.0,Tuvalu,NaN,NaN,NaN,NaN
217,217.0,United Arab Emirates,NaN,NaN,NaN,NaN
218,218.0,United Kingdom,NaN,NaN,NaN,NaN
219,219.0,United States,NaN,NaN,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN,NaN,NaN
221,221.0,Uruguay,NaN,NaN,NaN,NaN
223,223.0,Vanuatu,NaN,NaN,NaN,NaN
224,224.0,Vatican City,NaN,NaN,NaN,NaN
226,226.0,Vietnam,NaN,NaN,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN,NaN,NaN
228,228.0,Western Sahara,NaN,NaN,NaN,NaN
229,229.0,Yemen,NaN,NaN,NaN,NaN
230,230.0,Zambia,NaN,NaN,NaN,NaN
231,231.0,Zimbabwe,NaN,NaN,NaN,NaN
232,NaN,NaN,14.0,Côte d'Ivoire,Côte d'Ivoire,None
233,NaN,NaN,16.0,Chinese Taipei,China,China
234,NaN,NaN,33.0,Great Britain,Mauritania,Mauritania
235,NaN,NaN,36.0,"Hong Kong, China",Hong Kong,Hong Kong
236,NaN,NaN,41.0,Islamic Republic of Iran,Republic of the Congo,Republic of the Congo
237,NaN,NaN,49.0,Kosovo,Kosovo,None
238,NaN,NaN,64.0,People's Republic of China,Republic of the Congo,Republic of the Congo
239,NaN,NaN,70.0,Republic of Korea,Republic of the Congo,Republic of the Congo
240,NaN,NaN,71.0,Republic of Moldova,Republic of the Congo,Republic of the Congo
241,NaN,NaN,72.0,ROC,ROC,None
242,NaN,NaN,83.0,Syrian Arab Republic,Central African Republic,Central African Republic
243,NaN,NaN,90.0,United States of America,United States,United States

We can see that some associations have been correctly identified

* Hong Kong, China -> Hong Kong
* United States of America -> United States	

And some associations could not found correctly:
* Great Britain	-> 	United Kingdom
* Islamic Republic of Iran -> Iran
* People's Republic of China -> China
* Republic of Korea	-> South Korea
* Republic of Moldova -> Moldova
* ROC -> Russia
* Syrian Arab Republic -> Syria
* Chinese Taipei -> Taiwan
* Cote d'Ivoire	-> Ivory Coast

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [65]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[234, 'pop_fixed'] = "United Kingdom"
df_tmp.loc[236, 'pop_fixed'] = "Iran"
df_tmp.loc[238, 'pop_fixed'] = "China"
df_tmp.loc[239, 'pop_fixed'] = "South Korea"
df_tmp.loc[240, 'pop_fixed'] = "Moldova"
df_tmp.loc[241, 'pop_fixed'] = "Russia"
df_tmp.loc[242, 'pop_fixed'] = "Syria"
df_tmp.loc[233, 'pop_fixed'] = "Taiwan"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_tokyo.loc[index_tmp, df_tokyo.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_tokyo,"name", df_tokyo.columns[0])
df_tmp

index_primary        1
name                 1
index_ancillary    140
Country            140
dtype: int64

     index_primary                              name  index_ancillary Country
0              0.0                       Afghanistan              NaN     NaN
1              1.0                           Albania              NaN     NaN
2              2.0                           Algeria              NaN     NaN
3              3.0                    American Samoa              NaN     NaN
4              4.0                           Andorra              NaN     NaN
5              5.0                            Angola              NaN     NaN
6              6.0                          Anguilla              NaN     NaN
7              7.0               Antigua and Barbuda              NaN     NaN
10            10.0                             Aruba              NaN     NaN
16            16.0                        Bangladesh              NaN     NaN
17            17.0                          Barbados              NaN     NaN
20            20.0                            Belize              NaN     NaN
21            21.0                             Benin              NaN     NaN
23            23.0                            Bhutan              NaN     NaN
24            24.0                           Bolivia              NaN     NaN
25            25.0            Bosnia and Herzegovina              NaN     NaN
28            28.0            British Virgin Islands              NaN     NaN
29            29.0                            Brunei              NaN     NaN
32            32.0                           Burundi              NaN     NaN
33            33.0                          Cambodia              NaN     NaN
34            34.0                          Cameroon              NaN     NaN
36            36.0                        Cape Verde              NaN     NaN
37            37.0                    Cayman Islands              NaN     NaN
38            38.0          Central African Republic              NaN     NaN
39            39.0                              Chad              NaN     NaN
40            40.0                             Chile              NaN     NaN
43            43.0                           Comoros              NaN     NaN
44            44.0                      Cook Islands              NaN     NaN
45            45.0                        Costa Rica              NaN     NaN
48            48.0                           Curacao              NaN     NaN
49            49.0                            Cyprus              NaN     NaN
52            52.0                          Djibouti              NaN     NaN
53            53.0                          Dominica              NaN     NaN
55            55.0                          DR Congo              NaN     NaN
58            58.0                       El Salvador              NaN     NaN
59            59.0                 Equatorial Guinea              NaN     NaN
60            60.0                           Eritrea              NaN     NaN
62            62.0                          Eswatini              NaN     NaN
64            64.0                  Falkland Islands              NaN     NaN
65            65.0                     Faroe Islands              NaN     NaN
69            69.0                     French Guiana              NaN     NaN
70            70.0                  French Polynesia              NaN     NaN
71            71.0                             Gabon              NaN     NaN
72            72.0                            Gambia              NaN     NaN
76            76.0                         Gibraltar              NaN     NaN
78            78.0                         Greenland              NaN     NaN
80            80.0                        Guadeloupe              NaN     NaN
81            81.0                              Guam              NaN     NaN
82            82.0                         Guatemala              NaN     NaN
83            83.0                            Guinea              NaN     NaN
84            84.0                     Guinea-Bissau              NaN     NaN
85            85.0                            Guyana              NaN     NaN
86            86.0                             Haiti              NaN     NaN
87            87.0                          Honduras              NaN     NaN
90            90.0                           Iceland              NaN     NaN
94            94.0                              Iraq              NaN     NaN
96            96.0                       Isle of Man              NaN     NaN
105          105.0                          Kiribati              NaN     NaN
108          108.0                              Laos              NaN     NaN
110          110.0                           Lebanon              NaN     NaN
111          111.0                           Lesotho              NaN     NaN
112          112.0                           Liberia              NaN     NaN
113          113.0                             Libya              NaN     NaN
114          114.0                     Liechtenstein              NaN     NaN
116          116.0                        Luxembourg              NaN     NaN
117          117.0                             Macau              NaN     NaN
118          118.0                        Madagascar              NaN     NaN
119          119.0                            Malawi              NaN     NaN
121          121.0                          Maldives              NaN     NaN
122          122.0                              Mali              NaN     NaN
123          123.0                             Malta              NaN     NaN
124          124.0                  Marshall Islands              NaN     NaN
125          125.0                        Martinique              NaN     NaN
126          126.0                        Mauritania              NaN     NaN
127          127.0                         Mauritius              NaN     NaN
128          128.0                           Mayotte              NaN     NaN
130          130.0                        Micronesia              NaN     NaN
132          132.0                            Monaco              NaN     NaN
134          134.0                        Montenegro              NaN     NaN
135          135.0                        Montserrat              NaN     NaN
137          137.0                        Mozambique              NaN     NaN
138          138.0                           Myanmar              NaN     NaN
140          140.0                             Nauru              NaN     NaN
141          141.0                             Nepal              NaN     NaN
143          143.0                     New Caledonia              NaN     NaN
145          145.0                         Nicaragua              NaN     NaN
146          146.0                             Niger              NaN     NaN
148          148.0                              Niue              NaN     NaN
149          149.0                       North Korea              NaN     NaN
151          151.0          Northern Mariana Islands              NaN     NaN
153          153.0                              Oman              NaN     NaN
154          154.0                          Pakistan              NaN     NaN
155          155.0                             Palau              NaN     NaN
156          156.0                         Palestine              NaN     NaN
157          157.0                            Panama              NaN     NaN
158          158.0                  Papua New Guinea              NaN     NaN
159          159.0                          Paraguay              NaN     NaN
160          160.0                              Peru              NaN     NaN
166          166.0             Republic of the Congo              NaN     NaN
167          167.0                           Reunion              NaN     NaN
170          170.0                            Rwanda              NaN     NaN
171          171.0                  Saint Barthelemy              NaN     NaN
172          172.0             Saint Kitts and Nevis              NaN     NaN
173          173.0                       Saint Lucia              NaN     NaN
174          174.0                      Saint Martin              NaN     NaN
175          175.0         Saint Pierre and Miquelon              NaN     NaN
176          176.0  Saint Vincent and the Grenadines              NaN     NaN
177          177.0                             Samoa              NaN     NaN
179          179.0             Sao Tome and Principe              NaN     NaN
181          181.0                           Senegal              NaN     NaN
183          183.0                        Seychelles              NaN     NaN
184          184.0                      Sierra Leone              NaN     NaN
185          185.0                         Singapore              NaN     NaN
186          186.0                      Sint Maarten              NaN     NaN
189          189.0                   Solomon Islands              NaN     NaN
190          190.0                           Somalia              NaN     NaN
193          193.0                       South Sudan              NaN     NaN
195          195.0                         Sri Lanka              NaN     NaN
196          196.0                             Sudan              NaN     NaN
197          197.0                          Suriname              NaN     NaN
202          202.0                        Tajikistan              NaN     NaN
203          203.0                          Tanzania              NaN     NaN
205          205.0                       Timor-Leste              NaN     NaN
206          206.0                              Togo              NaN     NaN
207          207.0                           Tokelau              NaN     NaN
208          208.0                             Tonga              NaN     NaN
209          209.0               Trinidad and Tobago              NaN     NaN
213          213.0          Turks and Caicos Islands              NaN     NaN
214          214.0                            Tuvalu              NaN     NaN
217          217.0              United Arab Emirates              NaN     NaN
220          220.0      United States Virgin Islands              NaN     NaN
221          221.0                           Uruguay              NaN     NaN
223          223.0                           Vanuatu              NaN     NaN
224          224.0                      Vatican City              NaN     NaN
226          226.0                           Vietnam              NaN     NaN
227          227.0                 Wallis and Futuna              NaN     NaN
228          228.0                    Western Sahara              NaN     NaN
229          229.0                             Yemen              NaN     NaN
230          230.0                            Zambia              NaN     NaN
231          231.0                          Zimbabwe              NaN     NaN
232            NaN                               NaN             49.0  Kosovo

From the above we see that now only a single entry from the `df_tokyo` is unmatched i.e. Kosovo. This is because `df_population` has no record for 'Kosovo'.

The remaining records from `df_population` which are not matching is because these countries did not participate in the Tokyo Olympic 2020 games.

In [66]:
df_tokyo

,Country,Gold_Medal,Silver_Medal,Bronze_Medal,Total
index_ancillary,,,,,
0,Argentina,0,1,2,3
1,Armenia,0,2,2,4
2,Australia,17,7,22,46
3,Austria,1,1,5,7
4,Azerbaijan,0,3,4,7
5,Bahamas,2,0,0,2
6,Bahrain,0,1,0,1
7,Belarus,1,3,3,7
8,Belgium,3,1,3,7
9,Bermuda,1,0,0,1
10,Botswana,0,0,1,1
11,Brazil,7,6,8,21
12,Bulgaria,3,1,2,6
13,Burkina Faso,0,0,1,1
14,Ivory Coast,0,0,1,1
15,Canada,7,6,11,24
16,Taiwan,2,4,6,12
17,Colombia,0,4,1,5
18,Croatia,3,3,2,8
19,Cuba,7,3,5,15
20,Czech Republic,4,4,3,11
21,Denmark,3,4,4,11
22,Dominican Republic,0,3,2,5
23,Ecuador,2,1,0,3
24,Egypt,1,1,4,6
25,Estonia,1,0,1,2
26,Ethiopia,1,1,2,4
27,Fiji,1,0,1,2
28,Finland,0,0,2,2
29,France,10,12,11,33
30,Georgia,2,5,1,8
31,Germany,10,11,16,37
32,Ghana,0,0,1,1
33,United Kingdom,22,21,22,65
34,Greece,2,1,1,4
35,Grenada,0,0,1,1
36,Hong Kong,1,2,3,6
37,Hungary,6,7,7,20
38,India,1,2,4,7
39,Indonesia,1,1,3,5
40,Ireland,2,0,2,4
41,Iran,3,2,2,7
42,Israel,2,0,2,4
43,Italy,10,10,20,40
44,Jamaica,4,1,4,9
45,Japan,27,14,17,58
46,Jordan,0,1,1,2
47,Kazakhstan,0,0,8,8
48,Kenya,4,4,2,10
49,Kosovo,2,0,0,2
50,Kuwait,0,0,1,1
51,Kyrgyzstan,0,2,1,3
52,Latvia,1,0,1,2
53,Lithuania,0,1,0,1
54,Malaysia,0,1,1,2
55,Mexico,0,0,4,4
56,Mongolia,0,1,3,4
57,Morocco,1,0,0,1
58,Namibia,0,1,0,1
59,Netherlands,10,12,14,36
60,New Zealand,7,6,7,20
61,Nigeria,0,1,1,2
62,North Macedonia,0,1,0,1
63,Norway,4,2,2,8
64,China,38,32,18,88
65,Philippines,1,2,1,4
66,Poland,4,5,5,14
67,Portugal,1,1,2,4
68,Puerto Rico,1,0,0,1
69,Qatar,2,0,1,3
70,South Korea,6,4,10,20
71,Moldova,0,0,1,1
72,Russia,20,28,23,71
73,Romania,1,3,0,4
74,San Marino,0,1,2,3
75,Saudi Arabia,0,1,0,1
76,Serbia,3,1,5,9
77,Slovakia,1,2,1,4
78,Slovenia,3,1,1,5
79,South Africa,1,2,0,3
80,Spain,3,8,6,17
81,Sweden,3,6,0,9
82,Switzerland,3,4,6,13
83,Syria,0,0,1,1
84,Thailand,1,0,1,2
85,Tunisia,1,1,0,2
86,Turkey,2,2,9,13
87,Turkmenistan,0,1,0,1
88,Uganda,2,1,1,4
89,Ukraine,1,6,12,19
90,United States,39,41,33,113
91,Uzbekistan,3,0,2,5
92,Venezuela,1,3,0,4

In [67]:
del df_tmp

####  II. Match country names in `df_rio`:

In [68]:
df_tmp = find_divergence(df_rio, df_rio.columns[0])

df_tmp

index_primary        3
name                 3
index_ancillary    148
Country            148
dtype: int64

,index_primary,name,index_ancillary,Country,CnT-pad,CnT-noPad
0,0.0,Afghanistan,NaN,NaN,NaN,NaN
1,1.0,Albania,NaN,NaN,NaN,NaN
3,3.0,American Samoa,NaN,NaN,NaN,NaN
4,4.0,Andorra,NaN,NaN,NaN,NaN
5,5.0,Angola,NaN,NaN,NaN,NaN
6,6.0,Anguilla,NaN,NaN,NaN,NaN
7,7.0,Antigua and Barbuda,NaN,NaN,NaN,NaN
10,10.0,Aruba,NaN,NaN,NaN,NaN
16,16.0,Bangladesh,NaN,NaN,NaN,NaN
17,17.0,Barbados,NaN,NaN,NaN,NaN
20,20.0,Belize,NaN,NaN,NaN,NaN
21,21.0,Benin,NaN,NaN,NaN,NaN
22,22.0,Bermuda,NaN,NaN,NaN,NaN
23,23.0,Bhutan,NaN,NaN,NaN,NaN
24,24.0,Bolivia,NaN,NaN,NaN,NaN
25,25.0,Bosnia and Herzegovina,NaN,NaN,NaN,NaN
26,26.0,Botswana,NaN,NaN,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN,NaN,NaN
29,29.0,Brunei,NaN,NaN,NaN,NaN
31,31.0,Burkina Faso,NaN,NaN,NaN,NaN
33,33.0,Cambodia,NaN,NaN,NaN,NaN
34,34.0,Cameroon,NaN,NaN,NaN,NaN
36,36.0,Cape Verde,NaN,NaN,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN,NaN,NaN
38,38.0,Central African Republic,NaN,NaN,NaN,NaN
39,39.0,Chad,NaN,NaN,NaN,NaN
40,40.0,Chile,NaN,NaN,NaN,NaN
43,43.0,Comoros,NaN,NaN,NaN,NaN
44,44.0,Cook Islands,NaN,NaN,NaN,NaN
45,45.0,Costa Rica,NaN,NaN,NaN,NaN
48,48.0,Curacao,NaN,NaN,NaN,NaN
49,49.0,Cyprus,NaN,NaN,NaN,NaN
52,52.0,Djibouti,NaN,NaN,NaN,NaN
53,53.0,Dominica,NaN,NaN,NaN,NaN
55,55.0,DR Congo,NaN,NaN,NaN,NaN
56,56.0,Ecuador,NaN,NaN,NaN,NaN
58,58.0,El Salvador,NaN,NaN,NaN,NaN
59,59.0,Equatorial Guinea,NaN,NaN,NaN,NaN
60,60.0,Eritrea,NaN,NaN,NaN,NaN
62,62.0,Eswatini,NaN,NaN,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN,NaN,NaN
69,69.0,French Guiana,NaN,NaN,NaN,NaN
70,70.0,French Polynesia,NaN,NaN,NaN,NaN
71,71.0,Gabon,NaN,NaN,NaN,NaN
72,72.0,Gambia,NaN,NaN,NaN,NaN
75,75.0,Ghana,NaN,NaN,NaN,NaN
76,76.0,Gibraltar,NaN,NaN,NaN,NaN
78,78.0,Greenland,NaN,NaN,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN,NaN,NaN
81,81.0,Guam,NaN,NaN,NaN,NaN
82,82.0,Guatemala,NaN,NaN,NaN,NaN
83,83.0,Guinea,NaN,NaN,NaN,NaN
84,84.0,Guinea-Bissau,NaN,NaN,NaN,NaN
85,85.0,Guyana,NaN,NaN,NaN,NaN
86,86.0,Haiti,NaN,NaN,NaN,NaN
87,87.0,Honduras,NaN,NaN,NaN,NaN
88,88.0,Hong Kong,NaN,NaN,NaN,NaN
90,90.0,Iceland,NaN,NaN,NaN,NaN
94,94.0,Iraq,NaN,NaN,NaN,NaN
96,96.0,Isle of Man,NaN,NaN,NaN,NaN
99,99.0,Ivory Coast,NaN,NaN,NaN,NaN
105,105.0,Kiribati,NaN,NaN,NaN,NaN
106,106.0,Kuwait,NaN,NaN,NaN,NaN
107,107.0,Kyrgyzstan,NaN,NaN,NaN,NaN
108,108.0,Laos,NaN,NaN,NaN,NaN
109,109.0,Latvia,NaN,NaN,NaN,NaN
110,110.0,Lebanon,NaN,NaN,NaN,NaN
111,111.0,Lesotho,NaN,NaN,NaN,NaN
112,112.0,Liberia,NaN,NaN,NaN,NaN
113,113.0,Libya,NaN,NaN,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN,NaN,NaN
116,116.0,Luxembourg,NaN,NaN,NaN,NaN
117,117.0,Macau,NaN,NaN,NaN,NaN
118,118.0,Madagascar,NaN,NaN,NaN,NaN
119,119.0,Malawi,NaN,NaN,NaN,NaN
121,121.0,Maldives,NaN,NaN,NaN,NaN
122,122.0,Mali,NaN,NaN,NaN,NaN
123,123.0,Malta,NaN,NaN,NaN,NaN
124,124.0,Marshall Islands,NaN,NaN,NaN,NaN
125,125.0,Martinique,NaN,NaN,NaN,NaN
126,126.0,Mauritania,NaN,NaN,NaN,NaN
127,127.0,Mauritius,NaN,NaN,NaN,NaN
128,128.0,Mayotte,NaN,NaN,NaN,NaN
130,130.0,Micronesia,NaN,NaN,NaN,NaN
132,132.0,Monaco,NaN,NaN,NaN,NaN
134,134.0,Montenegro,NaN,NaN,NaN,NaN
135,135.0,Montserrat,NaN,NaN,NaN,NaN
137,137.0,Mozambique,NaN,NaN,NaN,NaN
138,138.0,Myanmar,NaN,NaN,NaN,NaN
139,139.0,Namibia,NaN,NaN,NaN,NaN
140,140.0,Nauru,NaN,NaN,NaN,NaN
141,141.0,Nepal,NaN,NaN,NaN,NaN
143,143.0,New Caledonia,NaN,NaN,NaN,NaN
145,145.0,Nicaragua,NaN,NaN,NaN,NaN
148,148.0,Niue,NaN,NaN,NaN,NaN
150,150.0,North Macedonia,NaN,NaN,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN,NaN,NaN
153,153.0,Oman,NaN,NaN,NaN,NaN
154,154.0,Pakistan,NaN,NaN,NaN,NaN
155,155.0,Palau,NaN,NaN,NaN,NaN
156,156.0,Palestine,NaN,NaN,NaN,NaN
157,157.0,Panama,NaN,NaN,NaN,NaN
158,158.0,Papua New Guinea,NaN,NaN,NaN,NaN
159,159.0,Paraguay,NaN,NaN,NaN,NaN
160,160.0,Peru,NaN,NaN,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN,NaN,NaN
167,167.0,Reunion,NaN,NaN,NaN,NaN
170,170.0,Rwanda,NaN,NaN,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN,NaN,NaN
172,172.0,Saint Kitts and Nevis,NaN,NaN,NaN,NaN
173,173.0,Saint Lucia,NaN,NaN,NaN,NaN
174,174.0,Saint Martin,NaN,NaN,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN
176,176.0,Saint Vincent and the Grenadines,NaN,NaN,NaN,NaN
177,177.0,Samoa,NaN,NaN,NaN,NaN
178,178.0,San Marino,NaN,NaN,NaN,NaN
179,179.0,Sao Tome and Principe,NaN,NaN,NaN,NaN
180,180.0,Saudi Arabia,NaN,NaN,NaN,NaN
181,181.0,Senegal,NaN,NaN,NaN,NaN
183,183.0,Seychelles,NaN,NaN,NaN,NaN
184,184.0,Sierra Leone,NaN,NaN,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN,NaN,NaN
189,189.0,Solomon Islands,NaN,NaN,NaN,NaN
190,190.0,Somalia,NaN,NaN,NaN,NaN
193,193.0,South Sudan,NaN,NaN,NaN,NaN
195,195.0,Sri Lanka,NaN,NaN,NaN,NaN
196,196.0,Sudan,NaN,NaN,NaN,NaN
197,197.0,Suriname,NaN,NaN,NaN,NaN
200,200.0,Syria,NaN,NaN,NaN,NaN
203,203.0,Tanzania,NaN,NaN,NaN,NaN
205,205.0,Timor-Leste,NaN,NaN,NaN,NaN
206,206.0,Togo,NaN,NaN,NaN,NaN
207,207.0,Tokelau,NaN,NaN,NaN,NaN
208,208.0,Tonga,NaN,NaN,NaN,NaN
212,212.0,Turkmenistan,NaN,NaN,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN,NaN,NaN
214,214.0,Tuvalu,NaN,NaN,NaN,NaN
215,215.0,Uganda,NaN,NaN,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN,NaN,NaN
221,221.0,Uruguay,NaN,NaN,NaN,NaN
223,223.0,Vanuatu,NaN,NaN,NaN,NaN
224,224.0,Vatican City,NaN,NaN,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN,NaN,NaN
228,228.0,Western Sahara,NaN,NaN,NaN,NaN
229,229.0,Yemen,NaN,NaN,NaN,NaN
230,230.0,Zambia,NaN,NaN,NaN,NaN
231,231.0,Zimbabwe,NaN,NaN,NaN,NaN
232,NaN,NaN,16.0,Cote d'Ivoire,Cote d'Ivoire,None
233,NaN,NaN,33.0,Independent Olympic Athletes,Independent Olympic Athletes,None
234,NaN,NaN,45.0,Kosovo,Kosovo,None

We can see that only one associations could not found correctly:
* Cote d'Ivoire	-> Ivory Coast

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [69]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Ivory Coast"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_rio.loc[index_tmp, df_rio.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_rio,"name", df_rio.columns[0])
df_tmp

index_primary        2
name                 2
index_ancillary    147
Country            147
dtype: int64

,index_primary,name,index_ancillary,Country
0,0.0,Afghanistan,NaN,NaN
1,1.0,Albania,NaN,NaN
3,3.0,American Samoa,NaN,NaN
4,4.0,Andorra,NaN,NaN
5,5.0,Angola,NaN,NaN
6,6.0,Anguilla,NaN,NaN
7,7.0,Antigua and Barbuda,NaN,NaN
10,10.0,Aruba,NaN,NaN
16,16.0,Bangladesh,NaN,NaN
17,17.0,Barbados,NaN,NaN
20,20.0,Belize,NaN,NaN
21,21.0,Benin,NaN,NaN
22,22.0,Bermuda,NaN,NaN
23,23.0,Bhutan,NaN,NaN
24,24.0,Bolivia,NaN,NaN
25,25.0,Bosnia and Herzegovina,NaN,NaN
26,26.0,Botswana,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN
29,29.0,Brunei,NaN,NaN
31,31.0,Burkina Faso,NaN,NaN
33,33.0,Cambodia,NaN,NaN
34,34.0,Cameroon,NaN,NaN
36,36.0,Cape Verde,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN
38,38.0,Central African Republic,NaN,NaN
39,39.0,Chad,NaN,NaN
40,40.0,Chile,NaN,NaN
43,43.0,Comoros,NaN,NaN
44,44.0,Cook Islands,NaN,NaN
45,45.0,Costa Rica,NaN,NaN
48,48.0,Curacao,NaN,NaN
49,49.0,Cyprus,NaN,NaN
52,52.0,Djibouti,NaN,NaN
53,53.0,Dominica,NaN,NaN
55,55.0,DR Congo,NaN,NaN
56,56.0,Ecuador,NaN,NaN
58,58.0,El Salvador,NaN,NaN
59,59.0,Equatorial Guinea,NaN,NaN
60,60.0,Eritrea,NaN,NaN
62,62.0,Eswatini,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN
69,69.0,French Guiana,NaN,NaN
70,70.0,French Polynesia,NaN,NaN
71,71.0,Gabon,NaN,NaN
72,72.0,Gambia,NaN,NaN
75,75.0,Ghana,NaN,NaN
76,76.0,Gibraltar,NaN,NaN
78,78.0,Greenland,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN
81,81.0,Guam,NaN,NaN
82,82.0,Guatemala,NaN,NaN
83,83.0,Guinea,NaN,NaN
84,84.0,Guinea-Bissau,NaN,NaN
85,85.0,Guyana,NaN,NaN
86,86.0,Haiti,NaN,NaN
87,87.0,Honduras,NaN,NaN
88,88.0,Hong Kong,NaN,NaN
90,90.0,Iceland,NaN,NaN
94,94.0,Iraq,NaN,NaN
96,96.0,Isle of Man,NaN,NaN
105,105.0,Kiribati,NaN,NaN
106,106.0,Kuwait,NaN,NaN
107,107.0,Kyrgyzstan,NaN,NaN
108,108.0,Laos,NaN,NaN
109,109.0,Latvia,NaN,NaN
110,110.0,Lebanon,NaN,NaN
111,111.0,Lesotho,NaN,NaN
112,112.0,Liberia,NaN,NaN
113,113.0,Libya,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN
116,116.0,Luxembourg,NaN,NaN
117,117.0,Macau,NaN,NaN
118,118.0,Madagascar,NaN,NaN
119,119.0,Malawi,NaN,NaN
121,121.0,Maldives,NaN,NaN
122,122.0,Mali,NaN,NaN
123,123.0,Malta,NaN,NaN
124,124.0,Marshall Islands,NaN,NaN
125,125.0,Martinique,NaN,NaN
126,126.0,Mauritania,NaN,NaN
127,127.0,Mauritius,NaN,NaN
128,128.0,Mayotte,NaN,NaN
130,130.0,Micronesia,NaN,NaN
132,132.0,Monaco,NaN,NaN
134,134.0,Montenegro,NaN,NaN
135,135.0,Montserrat,NaN,NaN
137,137.0,Mozambique,NaN,NaN
138,138.0,Myanmar,NaN,NaN
139,139.0,Namibia,NaN,NaN
140,140.0,Nauru,NaN,NaN
141,141.0,Nepal,NaN,NaN
143,143.0,New Caledonia,NaN,NaN
145,145.0,Nicaragua,NaN,NaN
148,148.0,Niue,NaN,NaN
150,150.0,North Macedonia,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN
153,153.0,Oman,NaN,NaN
154,154.0,Pakistan,NaN,NaN
155,155.0,Palau,NaN,NaN
156,156.0,Palestine,NaN,NaN
157,157.0,Panama,NaN,NaN
158,158.0,Papua New Guinea,NaN,NaN
159,159.0,Paraguay,NaN,NaN
160,160.0,Peru,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN
167,167.0,Reunion,NaN,NaN
170,170.0,Rwanda,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN
172,172.0,Saint Kitts and Nevis,NaN,NaN
173,173.0,Saint Lucia,NaN,NaN
174,174.0,Saint Martin,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN
176,176.0,Saint Vincent and the Grenadines,NaN,NaN
177,177.0,Samoa,NaN,NaN
178,178.0,San Marino,NaN,NaN
179,179.0,Sao Tome and Principe,NaN,NaN
180,180.0,Saudi Arabia,NaN,NaN
181,181.0,Senegal,NaN,NaN
183,183.0,Seychelles,NaN,NaN
184,184.0,Sierra Leone,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN
189,189.0,Solomon Islands,NaN,NaN
190,190.0,Somalia,NaN,NaN
193,193.0,South Sudan,NaN,NaN
195,195.0,Sri Lanka,NaN,NaN
196,196.0,Sudan,NaN,NaN
197,197.0,Suriname,NaN,NaN
200,200.0,Syria,NaN,NaN
203,203.0,Tanzania,NaN,NaN
205,205.0,Timor-Leste,NaN,NaN
206,206.0,Togo,NaN,NaN
207,207.0,Tokelau,NaN,NaN
208,208.0,Tonga,NaN,NaN
212,212.0,Turkmenistan,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN
214,214.0,Tuvalu,NaN,NaN
215,215.0,Uganda,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN
221,221.0,Uruguay,NaN,NaN
223,223.0,Vanuatu,NaN,NaN
224,224.0,Vatican City,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN
228,228.0,Western Sahara,NaN,NaN
229,229.0,Yemen,NaN,NaN
230,230.0,Zambia,NaN,NaN
231,231.0,Zimbabwe,NaN,NaN
232,NaN,NaN,33.0,Independent Olympic Athletes
233,NaN,NaN,45.0,Kosovo

For the below records of `df_rio`, there is no records in `df_population`:
* Independent Olympic Athletes
* Kosovo

The remaining records from `df_population` which are not matching is because these countries did not participate in the Rio Olympic 2016 games.

In [70]:
df_rio

                                      Country  Gold  Silver  Bronze  Total
index_ancillary
0                                     Algeria     0       2       0      2
1                                   Argentina     3       1       0      4
2                                     Armenia     1       3       0      4
3                                   Australia     8      11      10     19
4                                     Austria     0       0       1      0
5                                  Azerbaijan     1       7      10      8
6                                     Bahamas     1       0       1      1
7                                     Bahrain     1       1       0      2
8                                     Belarus     1       4       4      5
9                                     Belgium     2       2       2      4
10                                     Brazil     7       6       6     13
11                                   Bulgaria     0       1       2      1
12                                    Burundi     0       1       0      1
13                                     Canada     4       3      15      7
14                                      China    26      18      26     44
15                                   Colombia     3       2       3      5
16                                Ivory Coast     1       0       1      1
17                                    Croatia     5       3       2      8
18                                       Cuba     5       2       4      7
19                             Czech Republic     1       2       7      3
20                                    Denmark     2       6       7      8
21                         Dominican Republic     0       0       1      0
22                                      Egypt     0       0       3      0
23                                    Estonia     0       0       1      0
24                                   Ethiopia     1       2       5      3
25                                       Fiji     1       0       0      1
26                                    Finland     0       0       1      0
27                                     France    10      18      14     28
28                                    Georgia     2       1       4      3
29                                    Germany    17      10      15     27
30                                     Greece     3       1       2      4
31                                    Grenada     0       1       0      1
32                                    Hungary     8       3       4     11
33               Independent Olympic Athletes     1       0       1      1
34                                      India     0       1       1      1
35                                  Indonesia     1       2       0      3
36                                       Iran     3       1       4      4
37                                    Ireland     0       2       0      2
38                                     Israel     0       0       2      0
39                                      Italy     8      12       8     20
40                                    Jamaica     6       3       2      9
41                                      Japan    12       8      21     20
42                                     Jordan     1       0       0      1
43                                 Kazakhstan     3       5       9      8
44                                      Kenya     6       6       1     12
45                                     Kosovo     1       0       0      1
46                                  Lithuania     0       1       3      1
47                                   Malaysia     0       4       1      4
48                                     Mexico     0       3       2      3
49                                    Moldova     0       0       1      0
50                                   Mongolia     0       1       1      1
51                                    Morocco     0       0       1      0
52                                Netherlands     8       7       4     15
53                                New Zealand     4       9       5     13
54                                      Niger     0       1       0      1
55                                    Nigeria     0       0       1      0
56                                North Korea     2       3       2      5
57                                     Norway     0       0       4      0
58                                Philippines     0       1       0      1
59                                     Poland     2       3       6      5
60                                   Portugal     0       0       1      0
61                                Puerto Rico     1       0       0      1
62                                      Qatar     0       1       0      1
63                                    Romania     1       1       3      2
64                                     Russia    19      18      19     37
65                                     Serbia     2       4       2      6
66                                  Singapore     1       0       0      1
67                                   Slovakia     2       2       0      4
68                                   Slovenia     1       2       1      3
69                               South Africa     2       6       2      8
70                                South Korea     9       3       9     12
71                                      Spain     7       4       6     11
72                                     Sweden     2       6       3      8
73                                Switzerland     3       2       2      5
74                                     Taiwan     1       0       2      1
75                                 Tajikistan     1       0       0      1
76                                   Thailand     2       2       2      4
77                        Trinidad and Tobago     0       0       1      0
78                                    Tunisia     0       0       3      0
79                                     Turkey     1       3       4      4
80                                    Ukraine     2       5       4      7
81                       United Arab Emirates     0       0       1      0
82                             United Kingdom    27      23      17     50
83                              United States    46      37      38     83
84                                 Uzbekistan     4       2       7      6
85                                  Venezuela     0       1       2      1
86                                    Vietnam     1       1       0      2

In [71]:
del df_tmp

#### III. Match country names in `df_london`:

In [72]:
df_tmp = find_divergence(df_london, df_london.columns[0])

df_tmp

index_primary        9
name                 9
index_ancillary    156
Country            156
dtype: int64

,index_primary,name,index_ancillary,Country,CnT-pad,CnT-noPad
1,1.0,Albania,NaN,NaN,NaN,NaN
3,3.0,American Samoa,NaN,NaN,NaN,NaN
4,4.0,Andorra,NaN,NaN,NaN,NaN
5,5.0,Angola,NaN,NaN,NaN,NaN
6,6.0,Anguilla,NaN,NaN,NaN,NaN
7,7.0,Antigua and Barbuda,NaN,NaN,NaN,NaN
10,10.0,Aruba,NaN,NaN,NaN,NaN
12,12.0,Austria,NaN,NaN,NaN,NaN
16,16.0,Bangladesh,NaN,NaN,NaN,NaN
17,17.0,Barbados,NaN,NaN,NaN,NaN
20,20.0,Belize,NaN,NaN,NaN,NaN
21,21.0,Benin,NaN,NaN,NaN,NaN
22,22.0,Bermuda,NaN,NaN,NaN,NaN
23,23.0,Bhutan,NaN,NaN,NaN,NaN
24,24.0,Bolivia,NaN,NaN,NaN,NaN
25,25.0,Bosnia and Herzegovina,NaN,NaN,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN,NaN,NaN
29,29.0,Brunei,NaN,NaN,NaN,NaN
31,31.0,Burkina Faso,NaN,NaN,NaN,NaN
32,32.0,Burundi,NaN,NaN,NaN,NaN
33,33.0,Cambodia,NaN,NaN,NaN,NaN
36,36.0,Cape Verde,NaN,NaN,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN,NaN,NaN
38,38.0,Central African Republic,NaN,NaN,NaN,NaN
39,39.0,Chad,NaN,NaN,NaN,NaN
40,40.0,Chile,NaN,NaN,NaN,NaN
41,41.0,China,NaN,NaN,NaN,NaN
43,43.0,Comoros,NaN,NaN,NaN,NaN
44,44.0,Cook Islands,NaN,NaN,NaN,NaN
45,45.0,Costa Rica,NaN,NaN,NaN,NaN
48,48.0,Curacao,NaN,NaN,NaN,NaN
52,52.0,Djibouti,NaN,NaN,NaN,NaN
53,53.0,Dominica,NaN,NaN,NaN,NaN
55,55.0,DR Congo,NaN,NaN,NaN,NaN
56,56.0,Ecuador,NaN,NaN,NaN,NaN
58,58.0,El Salvador,NaN,NaN,NaN,NaN
59,59.0,Equatorial Guinea,NaN,NaN,NaN,NaN
60,60.0,Eritrea,NaN,NaN,NaN,NaN
62,62.0,Eswatini,NaN,NaN,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN,NaN,NaN
66,66.0,Fiji,NaN,NaN,NaN,NaN
69,69.0,French Guiana,NaN,NaN,NaN,NaN
70,70.0,French Polynesia,NaN,NaN,NaN,NaN
72,72.0,Gambia,NaN,NaN,NaN,NaN
75,75.0,Ghana,NaN,NaN,NaN,NaN
76,76.0,Gibraltar,NaN,NaN,NaN,NaN
78,78.0,Greenland,NaN,NaN,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN,NaN,NaN
81,81.0,Guam,NaN,NaN,NaN,NaN
83,83.0,Guinea,NaN,NaN,NaN,NaN
84,84.0,Guinea-Bissau,NaN,NaN,NaN,NaN
85,85.0,Guyana,NaN,NaN,NaN,NaN
86,86.0,Haiti,NaN,NaN,NaN,NaN
87,87.0,Honduras,NaN,NaN,NaN,NaN
88,88.0,Hong Kong,NaN,NaN,NaN,NaN
90,90.0,Iceland,NaN,NaN,NaN,NaN
93,93.0,Iran,NaN,NaN,NaN,NaN
94,94.0,Iraq,NaN,NaN,NaN,NaN
96,96.0,Isle of Man,NaN,NaN,NaN,NaN
97,97.0,Israel,NaN,NaN,NaN,NaN
99,99.0,Ivory Coast,NaN,NaN,NaN,NaN
102,102.0,Jordan,NaN,NaN,NaN,NaN
105,105.0,Kiribati,NaN,NaN,NaN,NaN
107,107.0,Kyrgyzstan,NaN,NaN,NaN,NaN
108,108.0,Laos,NaN,NaN,NaN,NaN
110,110.0,Lebanon,NaN,NaN,NaN,NaN
111,111.0,Lesotho,NaN,NaN,NaN,NaN
112,112.0,Liberia,NaN,NaN,NaN,NaN
113,113.0,Libya,NaN,NaN,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN,NaN,NaN
116,116.0,Luxembourg,NaN,NaN,NaN,NaN
117,117.0,Macau,NaN,NaN,NaN,NaN
118,118.0,Madagascar,NaN,NaN,NaN,NaN
119,119.0,Malawi,NaN,NaN,NaN,NaN
121,121.0,Maldives,NaN,NaN,NaN,NaN
122,122.0,Mali,NaN,NaN,NaN,NaN
123,123.0,Malta,NaN,NaN,NaN,NaN
124,124.0,Marshall Islands,NaN,NaN,NaN,NaN
125,125.0,Martinique,NaN,NaN,NaN,NaN
126,126.0,Mauritania,NaN,NaN,NaN,NaN
127,127.0,Mauritius,NaN,NaN,NaN,NaN
128,128.0,Mayotte,NaN,NaN,NaN,NaN
130,130.0,Micronesia,NaN,NaN,NaN,NaN
131,131.0,Moldova,NaN,NaN,NaN,NaN
132,132.0,Monaco,NaN,NaN,NaN,NaN
135,135.0,Montserrat,NaN,NaN,NaN,NaN
137,137.0,Mozambique,NaN,NaN,NaN,NaN
138,138.0,Myanmar,NaN,NaN,NaN,NaN
139,139.0,Namibia,NaN,NaN,NaN,NaN
140,140.0,Nauru,NaN,NaN,NaN,NaN
141,141.0,Nepal,NaN,NaN,NaN,NaN
143,143.0,New Caledonia,NaN,NaN,NaN,NaN
145,145.0,Nicaragua,NaN,NaN,NaN,NaN
146,146.0,Niger,NaN,NaN,NaN,NaN
147,147.0,Nigeria,NaN,NaN,NaN,NaN
148,148.0,Niue,NaN,NaN,NaN,NaN
149,149.0,North Korea,NaN,NaN,NaN,NaN
150,150.0,North Macedonia,NaN,NaN,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN,NaN,NaN
153,153.0,Oman,NaN,NaN,NaN,NaN
154,154.0,Pakistan,NaN,NaN,NaN,NaN
155,155.0,Palau,NaN,NaN,NaN,NaN
156,156.0,Palestine,NaN,NaN,NaN,NaN
157,157.0,Panama,NaN,NaN,NaN,NaN
158,158.0,Papua New Guinea,NaN,NaN,NaN,NaN
159,159.0,Paraguay,NaN,NaN,NaN,NaN
160,160.0,Peru,NaN,NaN,NaN,NaN
161,161.0,Philippines,NaN,NaN,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN,NaN,NaN
167,167.0,Reunion,NaN,NaN,NaN,NaN
169,169.0,Russia,NaN,NaN,NaN,NaN
170,170.0,Rwanda,NaN,NaN,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN,NaN,NaN
172,172.0,Saint Kitts and Nevis,NaN,NaN,NaN,NaN
173,173.0,Saint Lucia,NaN,NaN,NaN,NaN
174,174.0,Saint Martin,NaN,NaN,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN
176,176.0,Saint Vincent and the Grenadines,NaN,NaN,NaN,NaN
177,177.0,Samoa,NaN,NaN,NaN,NaN
178,178.0,San Marino,NaN,NaN,NaN,NaN
179,179.0,Sao Tome and Principe,NaN,NaN,NaN,NaN
181,181.0,Senegal,NaN,NaN,NaN,NaN
183,183.0,Seychelles,NaN,NaN,NaN,NaN
184,184.0,Sierra Leone,NaN,NaN,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN,NaN,NaN
189,189.0,Solomon Islands,NaN,NaN,NaN,NaN
190,190.0,Somalia,NaN,NaN,NaN,NaN
192,192.0,South Korea,NaN,NaN,NaN,NaN
193,193.0,South Sudan,NaN,NaN,NaN,NaN
195,195.0,Sri Lanka,NaN,NaN,NaN,NaN
196,196.0,Sudan,NaN,NaN,NaN,NaN
197,197.0,Suriname,NaN,NaN,NaN,NaN
200,200.0,Syria,NaN,NaN,NaN,NaN
201,201.0,Taiwan,NaN,NaN,NaN,NaN
203,203.0,Tanzania,NaN,NaN,NaN,NaN
205,205.0,Timor-Leste,NaN,NaN,NaN,NaN
206,206.0,Togo,NaN,NaN,NaN,NaN
207,207.0,Tokelau,NaN,NaN,NaN,NaN
208,208.0,Tonga,NaN,NaN,NaN,NaN
212,212.0,Turkmenistan,NaN,NaN,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN,NaN,NaN
214,214.0,Tuvalu,NaN,NaN,NaN,NaN
217,217.0,United Arab Emirates,NaN,NaN,NaN,NaN
218,218.0,United Kingdom,NaN,NaN,NaN,NaN
219,219.0,United States,NaN,NaN,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN,NaN,NaN
221,221.0,Uruguay,NaN,NaN,NaN,NaN
223,223.0,Vanuatu,NaN,NaN,NaN,NaN
224,224.0,Vatican City,NaN,NaN,NaN,NaN
226,226.0,Vietnam,NaN,NaN,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN,NaN,NaN
228,228.0,Western Sahara,NaN,NaN,NaN,NaN
229,229.0,Yemen,NaN,NaN,NaN,NaN
230,230.0,Zambia,NaN,NaN,NaN,NaN
231,231.0,Zimbabwe,NaN,NaN,NaN,NaN
232,NaN,NaN,15.0,Chinese Taipei,China,China
233,NaN,NaN,21.0,Democratic People's Republic of Korea,Democratic People's Republic of Korea,None
234,NaN,NaN,32.0,Great Britain,Mauritania,Mauritania
235,NaN,NaN,36.0,"Hong Kong, China",Hong Kong,Hong Kong
236,NaN,NaN,41.0,Islamic Republic of Iran,Republic of the Congo,Republic of the Congo
237,NaN,NaN,58.0,People's Republic of China,Republic of the Congo,Republic of the Congo
238,NaN,NaN,63.0,Republic of Korea,Republic of the Congo,Republic of the Congo
239,NaN,NaN,65.0,Russian Federation,Russia,Russia
240,NaN,NaN,82.0,United States of America,United States,United States

We can see that some associations have been correctly identified
* Hong Kong, China -> Hong Kong
* Russian Federation -> Russia	
* United States of America -> United States

And some associations could not found correctly:
* Chinese Taipei -> Taiwan
* Democratic People's Republic of Korea -> North Korea
* Great Britain	-> 	United Kingdom
* Islamic Republic of Iran -> Iran
* People's Republic of China -> China
* Republic of Korea	-> South Korea

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [73]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Taiwan"
df_tmp.loc[233, 'pop_fixed'] = "North Korea"
df_tmp.loc[234, 'pop_fixed'] = "United Kingdom"
df_tmp.loc[236, 'pop_fixed'] = "Iran"
df_tmp.loc[237, 'pop_fixed'] = "China"
df_tmp.loc[238, 'pop_fixed'] = "South Korea"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_london.loc[index_tmp, df_london.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_london,"name", df_london.columns[0])
df_tmp

index_primary        0
name                 0
index_ancillary    147
Country            147
dtype: int64

     index_primary                              name  index_ancillary Country
1                1                           Albania              NaN     NaN
3                3                    American Samoa              NaN     NaN
4                4                           Andorra              NaN     NaN
5                5                            Angola              NaN     NaN
6                6                          Anguilla              NaN     NaN
7                7               Antigua and Barbuda              NaN     NaN
10              10                             Aruba              NaN     NaN
12              12                           Austria              NaN     NaN
16              16                        Bangladesh              NaN     NaN
17              17                          Barbados              NaN     NaN
20              20                            Belize              NaN     NaN
21              21                             Benin              NaN     NaN
22              22                           Bermuda              NaN     NaN
23              23                            Bhutan              NaN     NaN
24              24                           Bolivia              NaN     NaN
25              25            Bosnia and Herzegovina              NaN     NaN
28              28            British Virgin Islands              NaN     NaN
29              29                            Brunei              NaN     NaN
31              31                      Burkina Faso              NaN     NaN
32              32                           Burundi              NaN     NaN
33              33                          Cambodia              NaN     NaN
36              36                        Cape Verde              NaN     NaN
37              37                    Cayman Islands              NaN     NaN
38              38          Central African Republic              NaN     NaN
39              39                              Chad              NaN     NaN
40              40                             Chile              NaN     NaN
43              43                           Comoros              NaN     NaN
44              44                      Cook Islands              NaN     NaN
45              45                        Costa Rica              NaN     NaN
48              48                           Curacao              NaN     NaN
52              52                          Djibouti              NaN     NaN
53              53                          Dominica              NaN     NaN
55              55                          DR Congo              NaN     NaN
56              56                           Ecuador              NaN     NaN
58              58                       El Salvador              NaN     NaN
59              59                 Equatorial Guinea              NaN     NaN
60              60                           Eritrea              NaN     NaN
62              62                          Eswatini              NaN     NaN
64              64                  Falkland Islands              NaN     NaN
65              65                     Faroe Islands              NaN     NaN
66              66                              Fiji              NaN     NaN
69              69                     French Guiana              NaN     NaN
70              70                  French Polynesia              NaN     NaN
72              72                            Gambia              NaN     NaN
75              75                             Ghana              NaN     NaN
76              76                         Gibraltar              NaN     NaN
78              78                         Greenland              NaN     NaN
80              80                        Guadeloupe              NaN     NaN
81              81                              Guam              NaN     NaN
83              83                            Guinea              NaN     NaN
84              84                     Guinea-Bissau              NaN     NaN
85              85                            Guyana              NaN     NaN
86              86                             Haiti              NaN     NaN
87              87                          Honduras              NaN     NaN
90              90                           Iceland              NaN     NaN
94              94                              Iraq              NaN     NaN
96              96                       Isle of Man              NaN     NaN
97              97                            Israel              NaN     NaN
99              99                       Ivory Coast              NaN     NaN
102            102                            Jordan              NaN     NaN
105            105                          Kiribati              NaN     NaN
107            107                        Kyrgyzstan              NaN     NaN
108            108                              Laos              NaN     NaN
110            110                           Lebanon              NaN     NaN
111            111                           Lesotho              NaN     NaN
112            112                           Liberia              NaN     NaN
113            113                             Libya              NaN     NaN
114            114                     Liechtenstein              NaN     NaN
116            116                        Luxembourg              NaN     NaN
117            117                             Macau              NaN     NaN
118            118                        Madagascar              NaN     NaN
119            119                            Malawi              NaN     NaN
121            121                          Maldives              NaN     NaN
122            122                              Mali              NaN     NaN
123            123                             Malta              NaN     NaN
124            124                  Marshall Islands              NaN     NaN
125            125                        Martinique              NaN     NaN
126            126                        Mauritania              NaN     NaN
127            127                         Mauritius              NaN     NaN
128            128                           Mayotte              NaN     NaN
130            130                        Micronesia              NaN     NaN
131            131                           Moldova              NaN     NaN
132            132                            Monaco              NaN     NaN
135            135                        Montserrat              NaN     NaN
137            137                        Mozambique              NaN     NaN
138            138                           Myanmar              NaN     NaN
139            139                           Namibia              NaN     NaN
140            140                             Nauru              NaN     NaN
141            141                             Nepal              NaN     NaN
143            143                     New Caledonia              NaN     NaN
145            145                         Nicaragua              NaN     NaN
146            146                             Niger              NaN     NaN
147            147                           Nigeria              NaN     NaN
148            148                              Niue              NaN     NaN
150            150                   North Macedonia              NaN     NaN
151            151          Northern Mariana Islands              NaN     NaN
153            153                              Oman              NaN     NaN
154            154                          Pakistan              NaN     NaN
155            155                             Palau              NaN     NaN
156            156                         Palestine              NaN     NaN
157            157                            Panama              NaN     NaN
158            158                  Papua New Guinea              NaN     NaN
159            159                          Paraguay              NaN     NaN
160            160                              Peru              NaN     NaN
161            161                       Philippines              NaN     NaN
166            166             Republic of the Congo              NaN     NaN
167            167                           Reunion              NaN     NaN
170            170                            Rwanda              NaN     NaN
171            171                  Saint Barthelemy              NaN     NaN
172            172             Saint Kitts and Nevis              NaN     NaN
173            173                       Saint Lucia              NaN     NaN
174            174                      Saint Martin              NaN     NaN
175            175         Saint Pierre and Miquelon              NaN     NaN
176            176  Saint Vincent and the Grenadines              NaN     NaN
177            177                             Samoa              NaN     NaN
178            178                        San Marino              NaN     NaN
179            179             Sao Tome and Principe              NaN     NaN
181            181                           Senegal              NaN     NaN
183            183                        Seychelles              NaN     NaN
184            184                      Sierra Leone              NaN     NaN
186            186                      Sint Maarten              NaN     NaN
189            189                   Solomon Islands              NaN     NaN
190            190                           Somalia              NaN     NaN
193            193                       South Sudan              NaN     NaN
195            195                         Sri Lanka              NaN     NaN
196            196                             Sudan              NaN     NaN
197            197                          Suriname              NaN     NaN
200            200                             Syria              NaN     NaN
203            203                          Tanzania              NaN     NaN
205            205                       Timor-Leste              NaN     NaN
206            206                              Togo              NaN     NaN
207            207                           Tokelau              NaN     NaN
208            208                             Tonga              NaN     NaN
212            212                      Turkmenistan              NaN     NaN
213            213          Turks and Caicos Islands              NaN     NaN
214            214                            Tuvalu              NaN     NaN
217            217              United Arab Emirates              NaN     NaN
220            220      United States Virgin Islands              NaN     NaN
221            221                           Uruguay              NaN     NaN
223            223                           Vanuatu              NaN     NaN
224            224                      Vatican City              NaN     NaN
226            226                           Vietnam              NaN     NaN
227            227                 Wallis and Futuna              NaN     NaN
228            228                    Western Sahara              NaN     NaN
229            229                             Yemen              NaN     NaN
230            230                            Zambia              NaN     NaN
231            231                          Zimbabwe              NaN     NaN

The remaining records from `df_population` which are not matching is because these countries did not participate in the London Olympic 2012 games.

In [74]:
df_london

,Country,Gold_Medal,Silver_Medal,Bronze_Medal,Total
index_ancillary,,,,,
0,Afghanistan,0,0,1,1
1,Algeria,1,0,0,1
2,Argentina,1,1,2,4
3,Armenia,0,1,1,2
4,Australia,8,15,12,35
5,Azerbaijan,2,2,6,10
6,Bahamas,1,0,0,1
7,Bahrain,1,0,0,1
8,Belarus,2,5,3,10
9,Belgium,0,1,2,3
10,Botswana,0,1,0,1
11,Brazil,3,5,9,17
12,Bulgaria,0,2,1,3
13,Cameroon,0,0,1,1
14,Canada,2,5,11,18
15,Taiwan,1,0,1,2
16,Colombia,1,3,4,8
17,Croatia,3,1,2,6
18,Cuba,5,3,7,15
19,Cyprus,0,1,0,1
20,Czech Republic,4,3,4,11
21,North Korea,4,0,2,6
22,Denmark,2,4,3,9
23,Dominican Republic,1,1,0,2
24,Egypt,0,3,1,4
25,Estonia,0,1,1,2
26,Ethiopia,3,2,2,7
27,Finland,0,2,1,3
28,France,11,11,13,35
29,Gabon,0,1,0,1
30,Georgia,1,2,3,6
31,Germany,11,20,13,44
32,United Kingdom,29,17,19,65
33,Greece,0,0,2,2
34,Grenada,1,0,0,1
35,Guatemala,0,1,0,1
36,Hong Kong,0,0,1,1
37,Hungary,8,4,6,18
38,India,0,2,4,6
39,Indonesia,0,2,1,3
40,Ireland,1,1,4,6
41,Iran,7,5,1,13
42,Italy,8,9,11,28
43,Jamaica,4,5,3,12
44,Japan,7,14,17,38
45,Kazakhstan,3,1,7,11
46,Kenya,2,4,7,13
47,Kuwait,0,0,1,1
48,Latvia,1,0,1,2
49,Lithuania,2,0,3,5
50,Malaysia,0,1,1,2
51,Mexico,1,3,4,8
52,Mongolia,0,2,3,5
53,Montenegro,0,1,0,1
54,Morocco,0,0,1,1
55,Netherlands,6,6,8,20
56,New Zealand,6,2,5,13
57,Norway,2,1,1,4
58,China,38,31,22,91
59,Poland,3,1,7,11
60,Portugal,0,1,0,1
61,Puerto Rico,0,1,1,2
62,Qatar,0,0,2,2
63,South Korea,13,9,8,30
64,Romania,2,5,2,9
65,Russia,20,19,28,67
66,Saudi Arabia,0,0,1,1
67,Serbia,1,1,2,4
68,Singapore,0,0,2,2
69,Slovakia,0,1,3,4
70,Slovenia,1,1,2,4
71,South Africa,4,1,1,6
72,Spain,4,10,4,18
73,Sweden,1,4,3,8
74,Switzerland,2,2,0,4
75,Tajikistan,0,0,1,1
76,Thailand,0,2,2,4
77,Trinidad and Tobago,1,1,2,4
78,Tunisia,2,0,1,3
79,Turkey,1,1,1,3
80,Uganda,1,0,0,1
81,Ukraine,5,4,10,19
82,United States,46,28,30,104
83,Uzbekistan,0,0,2,2
84,Venezuela,1,0,0,1

In [75]:
del df_tmp

####  IV. Match country names in `df_covid_vac`:

In [76]:
# get unique country name from the Covid_Vaccination table 
df = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])
df_tmp = find_divergence(df, df.columns[0])

df_tmp

index_primary      15
name               15
index_ancillary    23
Country_Name       23
dtype: int64

,index_primary,name,index_ancillary,Country_Name,CnT-pad,CnT-noPad
3,3.0,American Samoa,NaN,NaN,NaN,NaN
50,50.0,Czech Republic,NaN,NaN,NaN,NaN
55,55.0,DR Congo,NaN,NaN,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN,NaN,NaN
69,69.0,French Guiana,NaN,NaN,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN,NaN,NaN
81,81.0,Guam,NaN,NaN,NaN,NaN
99,99.0,Ivory Coast,NaN,NaN,NaN,NaN
117,117.0,Macau,NaN,NaN,NaN,NaN
125,125.0,Martinique,NaN,NaN,NaN,NaN
128,128.0,Mayotte,NaN,NaN,NaN,NaN
149,149.0,North Korea,NaN,NaN,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN,NaN,NaN
164,164.0,Puerto Rico,NaN,NaN,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN,NaN,NaN
167,167.0,Reunion,NaN,NaN,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN,NaN,NaN
174,174.0,Saint Martin,NaN,NaN,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN
205,205.0,Timor-Leste,NaN,NaN,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN,NaN,NaN
224,224.0,Vatican City,NaN,NaN,NaN,NaN
228,228.0,Western Sahara,NaN,NaN,NaN,NaN
232,NaN,NaN,24.0,Bonaire Sint Eustatius and Saba,Bonaire Sint Eustatius and Saba,None
233,NaN,NaN,44.0,Congo,DR Congo,DR Congo
234,NaN,NaN,47.0,Cote d'Ivoire,North Korea,North Korea
235,NaN,NaN,52.0,Czechia,Czech Republic,Czech Republic
236,NaN,NaN,53.0,Democratic Republic of Congo,Republic of the Congo,Republic of the Congo
237,NaN,NaN,66.0,Faeroe Islands,Faroe Islands,Faroe Islands
238,NaN,NaN,82.0,Guernsey,Guernsey,None
239,NaN,NaN,101.0,Jersey,Jersey,None
240,NaN,NaN,106.0,Kosovo,Kosovo,None
241,NaN,NaN,118.0,Macao,Macau,Macau
242,NaN,NaN,149.0,Northern Cyprus,Northern Mariana Islands,Northern Mariana Islands
243,NaN,NaN,160.0,Pitcairn,Pitcairn,None
244,NaN,NaN,167.0,Saint Helena,Saint Barthelemy,Saint Barthelemy
245,NaN,NaN,199.0,Timor,Timor-Leste,Timor-Leste
246,NaN,NaN,217.0,Vatican,Vatican City,Vatican City

We can see that only one associations have been correctly identified
* Czechia -> Czech Republic

And some associations could not found correctly:
* Congo -> Republic of the Congo
* Cote d'Ivoire	-> Ivory Coast
* Democratic Republic of Congo -> DR Congo

And here were also some mistakes:
* Northern Cyprus -> Northern Mariana Islands
* Saint Helena	-> Saint Barthelemy

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [77]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[233, 'pop_fixed'] = "Republic of the Congo"
df_tmp.loc[234, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[236, 'pop_fixed'] = "DR Congo"
df_tmp.loc[242, 'pop_fixed'] = "Northern Cyprus"
df_tmp.loc[244, 'pop_fixed'] = "Saint Helena"


# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df.loc[index_tmp, df.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df,"name", df.columns[0])
df_tmp

index_primary       7
name                7
index_ancillary    15
Country_Name       15
dtype: int64

,index_primary,name,index_ancillary,Country_Name
3,3.0,American Samoa,NaN,NaN
69,69.0,French Guiana,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN
81,81.0,Guam,NaN,NaN
125,125.0,Martinique,NaN,NaN
128,128.0,Mayotte,NaN,NaN
149,149.0,North Korea,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN
164,164.0,Puerto Rico,NaN,NaN
167,167.0,Reunion,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN
174,174.0,Saint Martin,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN
228,228.0,Western Sahara,NaN,NaN
232,NaN,NaN,24.0,Bonaire Sint Eustatius and Saba
233,NaN,NaN,82.0,Guernsey
234,NaN,NaN,101.0,Jersey
235,NaN,NaN,106.0,Kosovo
236,NaN,NaN,149.0,Northern Cyprus
237,NaN,NaN,160.0,Pitcairn
238,NaN,NaN,167.0,Saint Helena

The remaining records from `df_population` and `df_covid_vac` which are not matching is because these countries are not available in the other table respectively.


The following country name is different in `df_covid_vac`:

1. Congo -> Republic of the Congo
2. Cote d'Ivoire -> Ivory Coast
3. Democratic Republic of Congo -> DR Congo

So, we replace the country name in `df_covid_vac`.

In [78]:
old_val = ["Congo", "Cote d'Ivoire", "Democratic Republic of Congo"]
new_val = ["Republic of the Congo", "Ivory Coast", "DR Congo"]

df_covid_vac['location'] =  df_covid_vac['location'].replace(old_val,new_val)

In [79]:
df_covid_vac

,location,date,total_cases,new_cases,total_deaths,new_deaths,people_vaccinated,people_fully_vaccinated
0,Afghanistan,2020-02-24,5.0,5.0,0.0,0.0,0.0,0.0
1,Afghanistan,2020-02-25,5.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,2020-02-26,5.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,2020-02-27,5.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,2020-02-28,5.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
134875,Zimbabwe,2021-11-17,133557.0,52.0,4699.0,1.0,0.0,0.0
134876,Zimbabwe,2021-11-18,133593.0,36.0,4699.0,0.0,3583256.0,2727175.0
134877,Zimbabwe,2021-11-19,133593.0,0.0,4699.0,0.0,3625221.0,2737278.0
134878,Zimbabwe,2021-11-20,133615.0,22.0,4699.0,0.0,3651820.0,2744192.0
134879,Zimbabwe,2021-11-21,133647.0,32.0,4699.0,0.0,3672011.0,2747693.0

In [80]:
del df, df_tmp

#### V. Match country names in `df_gdp`:

In [81]:
df_tmp = find_divergence(df_gdp, df_gdp.columns[0])

df_tmp

index_primary      23
name               23
index_ancillary    58
Country            58
dtype: int64

,index_primary,name,index_ancillary,Country,CnT-pad,CnT-noPad
3,3.0,American Samoa,NaN,NaN,NaN,NaN
6,6.0,Anguilla,NaN,NaN,NaN,NaN
14,14.0,Bahamas,NaN,NaN,NaN,NaN
22,22.0,Bermuda,NaN,NaN,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN,NaN,NaN
29,29.0,Brunei,NaN,NaN,NaN,NaN
36,36.0,Cape Verde,NaN,NaN,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN,NaN,NaN
41,41.0,China,NaN,NaN,NaN,NaN
44,44.0,Cook Islands,NaN,NaN,NaN,NaN
47,47.0,Cuba,NaN,NaN,NaN,NaN
48,48.0,Curacao,NaN,NaN,NaN,NaN
55,55.0,DR Congo,NaN,NaN,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN,NaN,NaN
69,69.0,French Guiana,NaN,NaN,NaN,NaN
70,70.0,French Polynesia,NaN,NaN,NaN,NaN
72,72.0,Gambia,NaN,NaN,NaN,NaN
76,76.0,Gibraltar,NaN,NaN,NaN,NaN
78,78.0,Greenland,NaN,NaN,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN,NaN,NaN
81,81.0,Guam,NaN,NaN,NaN,NaN
88,88.0,Hong Kong,NaN,NaN,NaN,NaN
96,96.0,Isle of Man,NaN,NaN,NaN,NaN
99,99.0,Ivory Coast,NaN,NaN,NaN,NaN
107,107.0,Kyrgyzstan,NaN,NaN,NaN,NaN
108,108.0,Laos,NaN,NaN,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN,NaN,NaN
117,117.0,Macau,NaN,NaN,NaN,NaN
125,125.0,Martinique,NaN,NaN,NaN,NaN
128,128.0,Mayotte,NaN,NaN,NaN,NaN
130,130.0,Micronesia,NaN,NaN,NaN,NaN
132,132.0,Monaco,NaN,NaN,NaN,NaN
135,135.0,Montserrat,NaN,NaN,NaN,NaN
143,143.0,New Caledonia,NaN,NaN,NaN,NaN
148,148.0,Niue,NaN,NaN,NaN,NaN
149,149.0,North Korea,NaN,NaN,NaN,NaN
150,150.0,North Macedonia,NaN,NaN,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN,NaN,NaN
156,156.0,Palestine,NaN,NaN,NaN,NaN
166,166.0,Republic of the Congo,NaN,NaN,NaN,NaN
167,167.0,Reunion,NaN,NaN,NaN,NaN
169,169.0,Russia,NaN,NaN,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN,NaN,NaN
174,174.0,Saint Martin,NaN,NaN,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN
179,179.0,Sao Tome and Principe,NaN,NaN,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN,NaN,NaN
187,187.0,Slovakia,NaN,NaN,NaN,NaN
192,192.0,South Korea,NaN,NaN,NaN,NaN
193,193.0,South Sudan,NaN,NaN,NaN,NaN
201,201.0,Taiwan,NaN,NaN,NaN,NaN
207,207.0,Tokelau,NaN,NaN,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN,NaN,NaN
224,224.0,Vatican City,NaN,NaN,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN,NaN,NaN
228,228.0,Western Sahara,NaN,NaN,NaN,NaN
232,NaN,NaN,13.0,"Bahamas, The",Bahamas,Bahamas
233,NaN,NaN,26.0,Brunei Darussalam,Brunei,Brunei
234,NaN,NaN,30.0,Cabo Verde,Cape Verde,Cape Verde
235,NaN,NaN,37.0,"China, People's Republic of","China, People's Republic of",None
236,NaN,NaN,40.0,"Congo, Dem. Rep. of the","Congo, Dem. Rep. of the",None
237,NaN,NaN,41.0,"Congo, Republic of",Republic of the Congo,Republic of the Congo
238,NaN,NaN,46.0,Cte d'Ivoire,Cte d'Ivoire,None
239,NaN,NaN,63.0,"Gambia, The",Gambia,Gambia
240,NaN,NaN,75.0,Hong Kong SAR,Hong Kong,Hong Kong
241,NaN,NaN,91.0,"Korea, Republic of",Republic of the Congo,Republic of the Congo
242,NaN,NaN,92.0,Kosovo,Kosovo,None
243,NaN,NaN,94.0,Kyrgyz Republic,Kyrgyz Republic,None
244,NaN,NaN,95.0,Lao P.D.R.,Lao P.D.R.,None
245,NaN,NaN,103.0,Macao SAR,Macau,Macau
246,NaN,NaN,114.0,"Micronesia, Fed. States of",Micronesia,Micronesia
247,NaN,NaN,129.0,North Macedonia,North Macedonia,North Macedonia
248,NaN,NaN,144.0,Russian Federation,Russia,Russia
249,NaN,NaN,157.0,Slovak Republic,Slovakia,Slovakia
250,NaN,NaN,162.0,"South Sudan, Republic of",South Sudan,South Sudan
251,NaN,NaN,170.0,So Tom and Prncipe,Sao Tome and Principe,Sao Tome and Principe
252,NaN,NaN,171.0,Taiwan Province of China,Taiwan Province of China,None
253,NaN,NaN,193.0,West Bank and Gaza,Western Sahara,Western Sahara
254,NaN,NaN,197.0,Africa,American Samoa,American Samoa

We can see that some associations have been correctly identified
* Bahamas, The -> Bahamas
* Brunei Darussalam	-> Brunei	
* Cabo Verde -> Cape Verde
* Congo, Republic of -> Republic of the Congo
* Gambia, The -> Gambia	
* Hong Kong SAR	-> Hong Kong
* Macao -> SAR	Macau
* Micronesia, Fed. States of -> Micronesia
* Russian Federation -> Russia
* Slovak Republic -> Slovakia	
* South Sudan, Republic of	-> South Sudan
* So Tom and Prncipe ->	Sao Tome and Principe	

And some associations could not found:
* China, People's Republic of -> China
* Congo, Dem. Rep. of the -> DR Congo
* Cte d'Ivoire	-> 	Ivory Coast
* Korea, Republic of -> South Korea
* Kyrgyz Republic	-> Kyrgyzstan
* Lao P.D.R. -> Laos
* Taiwan Province of China -> Taiwan

And here were also many mistakes.
* West Bank and Gaza -> Western Sahara	
* Africa -> American Samoa


So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [82]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[235, 'pop_fixed'] = 'China'
df_tmp.loc[236, 'pop_fixed'] = "DR Congo"
df_tmp.loc[238, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[241, 'pop_fixed'] = "South Korea"
df_tmp.loc[243, 'pop_fixed'] = 'Kyrgyzstan'
df_tmp.loc[244, 'pop_fixed'] = 'Laos'
df_tmp.loc[252, 'pop_fixed'] = "Taiwan"

df_tmp.loc[253, 'pop_fixed'] = "West Bank and Gaza"
df_tmp.loc[254, 'pop_fixed'] = "Africa"

# Now put the obtained values back into the df_2 table with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_gdp.loc[index_tmp, df_gdp.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_gdp,"name", df_gdp.columns[0])
df_tmp

index_primary       3
name                3
index_ancillary    38
Country            38
dtype: int64

,index_primary,name,index_ancillary,Country
3,3.0,American Samoa,NaN,NaN
6,6.0,Anguilla,NaN,NaN
22,22.0,Bermuda,NaN,NaN
28,28.0,British Virgin Islands,NaN,NaN
37,37.0,Cayman Islands,NaN,NaN
44,44.0,Cook Islands,NaN,NaN
47,47.0,Cuba,NaN,NaN
48,48.0,Curacao,NaN,NaN
64,64.0,Falkland Islands,NaN,NaN
65,65.0,Faroe Islands,NaN,NaN
69,69.0,French Guiana,NaN,NaN
70,70.0,French Polynesia,NaN,NaN
76,76.0,Gibraltar,NaN,NaN
78,78.0,Greenland,NaN,NaN
80,80.0,Guadeloupe,NaN,NaN
81,81.0,Guam,NaN,NaN
96,96.0,Isle of Man,NaN,NaN
114,114.0,Liechtenstein,NaN,NaN
125,125.0,Martinique,NaN,NaN
128,128.0,Mayotte,NaN,NaN
132,132.0,Monaco,NaN,NaN
135,135.0,Montserrat,NaN,NaN
143,143.0,New Caledonia,NaN,NaN
148,148.0,Niue,NaN,NaN
149,149.0,North Korea,NaN,NaN
151,151.0,Northern Mariana Islands,NaN,NaN
156,156.0,Palestine,NaN,NaN
167,167.0,Reunion,NaN,NaN
171,171.0,Saint Barthelemy,NaN,NaN
174,174.0,Saint Martin,NaN,NaN
175,175.0,Saint Pierre and Miquelon,NaN,NaN
186,186.0,Sint Maarten,NaN,NaN
207,207.0,Tokelau,NaN,NaN
213,213.0,Turks and Caicos Islands,NaN,NaN
220,220.0,United States Virgin Islands,NaN,NaN
224,224.0,Vatican City,NaN,NaN
227,227.0,Wallis and Futuna,NaN,NaN
228,228.0,Western Sahara,NaN,NaN
232,NaN,NaN,92.0,Kosovo
233,NaN,NaN,193.0,West Bank and Gaza
234,NaN,NaN,197.0,Africa

The remaining records from `df_population` and `df_gdp` which are not matching is because these countries are not available in the other table respectively.

In [83]:
df_gdp

,Country,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
index_ancillary,,,,,,,,,,,
1,Afghanistan,20.293,20.17,20.616,20.057,18.02,18.883,18.401,18.876,20.136,0
2,Albania,12.324,12.784,13.246,11.389,11.862,13.053,15.147,15.283,14.828,16.77
3,Algeria,209.059,209.755,213.81,165.979,160.034,170.207,175.367,171.07,147.6,163.812
4,Andorra,3.189,3.193,3.267,2.789,2.895,2.993,3.217,3.155,2.858,3.213
5,Angola,128.053,136.71,145.712,116.194,101.124,122.022,101.353,84.516,58.376,70.339
6,Antigua and Barbuda,1.2,1.181,1.25,1.337,1.437,1.468,1.605,1.687,1.37,1.405
7,Argentina,579.666,611.471,563.614,642.464,556.774,643.861,524.431,451.815,389.064,455.172
8,Armenia,10.619,11.121,11.61,10.553,10.546,11.527,12.458,13.619,12.641,13.612
9,Aruba,2.615,2.728,2.791,2.963,2.984,3.092,3.202,3.31,2.497,2.865
10,Australia,1569.311,1518.426,1457.381,1234.838,1266.196,1385.202,1421.194,1392.328,1359.372,1610.556
11,Austria,409.661,430.197,442.699,382.01,395.728,417.091,455.301,445.125,432.524,481.209
12,Azerbaijan,69.687,74.16,75.24,50.844,37.83,41.375,47.113,48.174,42.607,52.645
13,Bahamas,10.72,10.495,11.143,11.891,11.993,12.36,12.838,13.164,9.908,10.681
14,Bahrain,30.749,32.539,33.388,31.051,32.235,35.474,37.652,38.467,34.729,39.104
15,Bangladesh,133.304,150.026,172.887,195.147,221.398,249.695,273.3,302.397,323.057,355.689
16,Barbados,4.61,4.677,4.696,4.715,4.83,4.978,5.087,5.298,4.418,4.648
17,Belarus,65.669,75.496,78.736,56.329,47.703,54.723,60.011,64.414,60.201,65.754
18,Belgium,496.467,521.799,535.529,462.383,475.931,502.587,543.923,533.313,514.92,581.848
19,Belize,1.523,1.579,1.667,1.722,1.789,1.859,1.916,1.983,1.706,1.909
20,Benin,11.148,12.518,13.288,11.389,11.818,12.697,14.257,14.392,15.674,18.067
21,Bhutan,1.772,1.805,1.784,1.922,2.025,2.365,2.411,2.488,2.503,2.48
22,Bolivia,27.282,30.883,33.237,33.241,34.189,37.782,40.581,41.193,36.839,38.547
23,Bosnia and Herzegovina,17.207,18.155,18.522,16.21,16.91,18.081,20.184,20.203,19.789,21.692
24,Botswana,15.519,14.368,15.663,13.602,15.094,16.068,16.914,16.592,15.064,17.605
25,Brazil,2464.054,2471.718,2456.055,1800.046,1796.622,2063.518,1916.934,1877.822,1444.718,1645.837
26,Brunei,19.047,18.092,17.098,12.931,11.399,12.128,13.568,13.47,12.003,15.686
27,Bulgaria,54.031,55.617,56.902,50.647,53.802,59.093,66.294,68.563,69.209,77.907
28,Burkina Faso,12.569,13.444,13.947,11.833,12.83,14.102,16.067,15.991,17.378,19.932
29,Burundi,2.333,2.456,2.706,3.104,2.96,3.172,3.037,3.012,3.04,3.193
30,Cape Verde,1.742,1.85,1.86,1.597,1.663,1.77,1.967,1.982,1.707,1.886
31,Cambodia,14.057,15.228,16.702,18.083,20.043,22.208,24.599,27.088,25.192,26.08
32,Cameroon,29.121,32.358,34.999,30.932,32.635,34.997,38.712,39.009,39.938,44.806
33,Canada,1828.362,1846.595,1805.751,1556.508,1527.996,1649.266,1721.822,1741.576,1644.037,2015.983
34,Central African Republic,2.512,1.692,1.896,1.696,1.825,2.072,2.28,2.277,2.387,2.587
35,Chad,12.411,12.994,14.003,10.952,10.202,10.079,11.036,10.934,10.836,12.345
36,Chile,267.021,278.347,260.473,243.89,250.332,276.929,297.501,279.338,252.821,331.25
37,China,8539.584,9624.928,10524.241,11113.508,11226.897,12265.327,13841.812,14340.6,14866.741,16862.979
38,Colombia,370.691,382.093,381.241,293.493,282.72,311.89,334.124,323.375,271.554,300.791
39,Comoros,1.016,1.116,1.15,0.966,1.013,1.077,1.179,1.188,1.216,1.281
40,DR Congo,29.35,32.695,35.911,37.915,36.64,37.981,47.146,50.399,48.707,54.832
41,Republic of the Congo,17.704,17.959,17.918,11.891,10.159,11.11,13.649,12.791,10.329,12.744
42,Costa Rica,47.231,50.949,52.017,56.442,58.847,60.517,62.422,64.067,61.833,61.46
43,Croatia,56.581,58.194,57.64,49.526,51.601,55.482,61.375,60.752,56.171,63.399
44,Cyprus,24.993,23.9,23.162,19.844,20.947,22.721,25.322,24.953,23.785,26.546
45,Czech Republic,208.858,211.686,209.359,188.033,196.272,218.629,248.95,252.498,245.349,276.914
46,Ivory Coast,37.03,43.228,48.882,45.815,47.964,51.588,58.011,58.539,61.231,68.845
47,Denmark,327.149,343.584,352.994,302.673,313.116,332.121,356.841,347.561,356.085,396.666
48,Djibouti,1.9,2.043,2.216,2.445,2.619,2.767,3.013,3.346,3.44,3.654
49,Dominica,0.486,0.498,0.52,0.541,0.576,0.54,0.564,0.616,0.544,0.571
50,Dominican Republic,60.747,62.758,67.264,71.254,75.777,80.082,85.63,89.032,78.923,89.502
51,Ecuador,87.925,95.13,101.726,99.29,99.938,104.296,107.562,108.108,98.808,104.483
52,Egypt,278.769,288.007,305.567,332.075,332.484,236.528,250.253,302.335,363.245,396.328
53,El Salvador,21.386,21.991,22.593,23.438,24.191,24.979,26.021,26.897,24.639,27.665
54,Equatorial Guinea,22.388,21.949,21.765,13.185,11.241,12.201,13.097,11.417,10.036,12.528
55,Eritrea,2.255,1.958,2.604,2.016,2.213,1.904,2.006,1.982,2.084,2.254
56,Estonia,23.034,25.116,26.641,22.893,24.066,26.915,30.503,31.049,30.626,36.039
57,Eswatini,4.887,4.6,4.426,4.061,3.815,4.407,4.666,4.471,3.981,4.517
58,Ethiopia,42.221,46.544,54.165,63.081,72.12,76.841,80.207,92.608,96.611,92.757
59,Fiji,4.303,4.539,4.857,4.682,4.93,5.353,5.581,5.496,4.494,4.639
60,Finland,258.454,271.366,274.934,234.558,240.705,255.558,275.84,268.812,269.557,296.016
61,France,2683.893,2811.04,2852.171,2438.208,2471.261,2589.031,2789.68,2728.834,2624.416,2940.428
62,Gabon,17.181,17.596,18.209,14.385,14.02,14.924,16.875,16.875,15.339,18.293
63,Gambia,1.415,1.376,1.229,1.355,1.47,1.498,1.662,1.806,1.862,2.042
64,Georgia,16.489,17.19,17.627,14.953,15.141,16.242,17.599,17.477,15.891,17.846
65,Germany,3529.377,3733.859,3890.095,3357.926,3468.896,3689.547,3979.093,3888.756,3843.335,4230.172
66,Ghana,56.853,63.703,54.285,49.437,56.144,60.385,67.259,68.353,68.498,75.487
67,Greece,242.193,238.555,235.669,195.416,192.81,200.055,212.346,205.349,189.259,211.645
68,Grenada,0.8,0.843,0.911,0.997,1.062,1.126,1.167,1.188,1.027,1.083
69,Guatemala,49.902,52.989,57.835,62.18,66.034,71.624,73.212,77.004,77.603,83.305
70,Guinea,7.304,8.374,8.777,8.79,8.604,10.325,11.857,13.514,15.388,16.724
71,Guinea-Bissau,1.05,1.11,1.136,1.153,1.245,1.469,1.506,1.44,1.434,1.592
72,Guyana,4.063,4.168,4.128,4.28,4.483,4.748,4.788,5.174,5.471,7.395
73,Haiti,13.709,14.904,15.137,14.831,13.996,15.036,16.454,14.787,14.508,20.143
74,Honduras,18.529,18.5,19.757,20.98,21.718,23.136,24.068,25.09,23.828,26.325
75,Hong Kong,262.629,275.697,291.46,309.386,320.84,341.242,361.692,363.016,346.584,369.722
76,Hungary,128.475,135.412,140.765,125.074,128.471,142.962,160.431,163.494,155.013,180.959
77,Iceland,14.752,16.125,17.868,17.517,20.793,24.728,26.267,24.858,21.718,25.476
78,India,1827.637,1856.721,2039.127,2103.588,2294.118,2651.474,2701.112,2870.504,2660.244,2946.061
79,Indonesia,919.002,916.646,891.051,860.741,932.066,1015.488,1042.711,1120.042,1059.638,1150.245
80,Iran,392.295,400.087,433.088,385.023,418.064,445.528,456.59,581.252,835.351,1081.383
81,Iraq,218.032,234.638,234.651,177.634,167.716,192.343,226.87,233.953,169.488,201.472
82,Ireland,225.64,238.282,259.037,291.611,298.846,335.312,385.215,399.165,425.549,516.253
83,Israel,258.417,294.167,310.945,300.078,319.025,355.277,373.641,397.935,407.101,467.532
84,Italy,2088.278,2141.954,2162.567,1836.824,1876.554,1961.104,2093.088,2005.135,1884.935,2120.232
85,Jamaica,14.765,14.213,13.865,14.154,14.108,14.755,15.648,15.808,13.967,14.857
86,Japan,6272.364,5212.328,4896.995,4444.931,5003.678,4930.837,5036.892,5135.896,5045.101,5103.11
87,Jordan,31.679,34.503,36.9,38.642,39.949,41.467,42.993,44.566,43.759,45.344
88,Kazakhstan,207.999,236.635,221.416,184.388,137.289,166.806,179.34,181.667,171.24,194.024
89,Kenya,56.407,61.703,68.395,70.369,74.817,81.964,92.227,100.458,102.427,109.491
90,Kiribati,0.19,0.186,0.18,0.171,0.178,0.187,0.2,0.198,0.198,0.232
91,South Korea,1278.046,1370.633,1484.489,1466.039,1499.362,1623.074,1725.373,1651.423,1638.258,1823.852
92,Kosovo,6.504,7.074,7.398,6.444,6.717,7.243,7.947,7.953,7.78,8.958
93,Kuwait,174.066,174.179,162.695,114.606,109.381,120.687,138.202,136.192,105.949,132.266
94,Kyrgyzstan,6.604,7.335,7.467,6.678,6.813,7.703,8.271,8.872,7.747,8.15
95,Laos,10.195,11.974,13.266,14.363,15.905,17.055,18.131,18.771,18.82,19.375
96,Latvia,28.346,30.442,31.379,27.253,28.064,30.448,34.432,34.059,33.478,37.199
97,Lebanon,44.036,46.909,48.133,50.066,51.389,53.325,55.276,52.371,19.008,0
98,Lesotho,2.465,2.345,2.477,2.207,2.219,2.356,2.32,2.228,1.999,2.478
99,Liberia,2.675,3.044,3.09,3.092,3.256,3.321,3.264,3.08,3.037,3.384
100,Libya,79.759,51.896,24.262,17.216,18.563,30.211,41.432,39.497,19.21,27.3
101,Lithuania,42.952,46.537,48.611,41.44,43.035,47.742,53.747,54.646,55.843,62.635
102,Luxembourg,56.711,61.758,66.209,57.773,60.716,64.159,70.952,71.113,73.205,83.771
103,Macau,43.19,51.536,54.903,45.06,45.085,50.457,55.303,55.154,24.333,29.223
104,Madagascar,11.579,12.424,12.523,11.323,11.849,13.176,13.76,14.105,13.179,14.101
105,Malawi,8.421,7.648,8.526,9.014,7.733,8.943,9.882,11.031,11.847,12.15
106,Malaysia,318.91,327.869,342.868,301.355,301.255,319.109,358.789,365.279,337.008,371.114
107,Maldives,2.885,3.286,3.69,4.098,4.367,4.747,5.293,5.632,3.738,4.573
108,Mali,12.45,13.243,14.369,13.106,14.022,15.36,17.079,17.281,17.491,19.563
109,Malta,9.468,10.551,11.629,11.093,11.693,13.506,15.335,15.728,14.899,16.695
110,Marshall Islands,0.181,0.185,0.182,0.184,0.201,0.212,0.222,0.236,0.244,0.241
111,Mauritania,6.721,7.331,6.615,6.182,6.414,6.826,7.351,7.889,8.11,9.164
112,Mauritius,11.669,12.13,12.803,11.692,12.232,13.259,14.182,14.046,10.921,10.998
113,Mexico,1201.094,1274.444,1315.356,1171.87,1078.493,1158.912,1222.406,1269.432,1073.915,1285.518
114,Micronesia,0.327,0.317,0.319,0.316,0.332,0.367,0.402,0.413,0.407,0.404
115,Moldova,8.708,9.496,9.51,7.726,8.072,9.67,11.457,11.972,11.912,12.396
116,Mongolia,12.278,12.582,12.227,11.75,11.159,11.426,13.138,13.997,13.137,14.28
117,Montenegro,4.09,4.466,4.595,4.055,4.376,4.855,5.509,5.543,4.786,5.494
118,Morocco,98.266,106.826,110.081,101.179,103.312,109.683,118.096,119.871,114.602,126.035
119,Mozambique,16.351,16.974,17.716,15.951,11.937,13.219,14.845,15.39,14.029,15.833
120,Myanmar,59,60.903,63.153,62.655,60.09,61.267,66.699,68.802,81.257,66.74
121,Namibia,13.016,12.168,12.434,11.45,10.719,12.883,13.675,12.563,10.71,12.213
122,Nauru,0.097,0.099,0.105,0.087,0.1,0.11,0.124,0.119,0.114,0.133
123,Nepal,21.703,22.161,22.722,24.361,24.524,28.972,33.112,34.186,33.983,34.265
124,Netherlands,839.455,877.186,892.398,765.65,783.844,833.575,914.458,910.295,913.134,1007.562
125,New Zealand,175.032,187.168,200.142,176.213,185.956,203.842,210.005,210.443,209.384,247.64
126,Nicaragua,10.532,10.983,11.88,12.757,13.286,13.786,13.025,12.625,12.62,13.397
127,Niger,9.412,10.206,10.83,9.684,10.35,11.185,12.85,12.912,13.761,15.637
128,Nigeria,460.952,514.966,568.499,492.437,404.649,375.745,421.737,448.12,429.423,480.482
129,North Macedonia,9.751,10.824,11.378,10.067,10.686,11.336,12.694,12.55,12.288,13.885
130,Norway,509.506,522.762,498.41,385.802,368.827,398.394,437,405.51,362.522,445.507
131,Oman,76.616,78.784,81.077,68.919,65.481,70.598,79.789,76.332,63.368,80.611
132,Pakistan,223.119,230.644,243.94,270.17,278.023,304.603,313.073,276.942,261.726,0
133,Palau,0.212,0.224,0.243,0.29,0.3,0.287,0.286,0.275,0.257,0.208
134,Panama,40.43,45.6,49.921,54.092,57.908,62.203,64.928,66.788,52.938,60.121
135,Papua New Guinea,21.295,21.261,23.211,21.723,20.759,22.743,24.11,24.829,23.279,26.461
136,Paraguay,33.296,38.651,40.378,36.211,36.09,38.997,40.225,37.907,35.67,36.973
137,Peru,192.85,202.082,202.278,191.247,194.266,214.128,225.369,230.865,205.458,225.858
138,Philippines,261.92,283.903,297.484,306.446,318.627,328.481,346.842,376.823,361.489,385.737
139,Poland,498.517,521.013,542.602,477.488,472.256,526.643,587.433,597.194,595.916,655.332
140,Portugal,216.361,226.437,229.961,199.414,206.369,221.28,242.423,240.013,228.356,251.709
141,Puerto Rico,101.565,102.45,102.446,103.376,104.337,103.446,104.925,104.915,103.138,106.576
142,Qatar,186.834,198.728,206.225,161.74,151.732,161.099,183.335,175.838,145.45,169.184
143,Romania,170.636,190.8,199.961,177.731,188.13,211.696,241.456,249.695,248.716,287.279
144,Russia,2191.484,2288.428,2048.836,1356.704,1280.648,1575.14,1653.005,1690.05,1478.571,1647.568
145,Rwanda,7.651,7.816,8.234,8.542,8.691,9.253,9.641,10.356,10.332,10.395
146,Saint Kitts and Nevis,0.826,0.875,0.954,0.958,1.009,1.061,1.079,1.165,0.981,0.976
147,Saint Lucia,1.606,1.666,1.756,1.81,1.866,1.997,2.065,2.119,1.617,1.715
148,Saint Vincent and the Grenadines,0.693,0.721,0.728,0.755,0.774,0.792,0.811,0.825,0.807,0.769
149,Samoa,0.759,0.764,0.757,0.788,0.799,0.832,0.837,0.846,0.812,0.78
150,San Marino,1.606,1.678,1.674,1.42,1.468,1.528,1.656,1.616,1.554,1.728
151,Saudi Arabia,735.975,746.647,756.35,654.27,644.935,688.586,786.522,792.966,700.118,842.588
152,Senegal,17.672,18.919,19.802,17.777,19.035,20.989,23.127,23.307,24.681,27.576
153,Serbia,43.33,48.428,47.095,39.656,40.693,44.179,50.641,51.475,52.96,60.669
154,Seychelles,1.06,1.328,1.343,1.377,1.426,1.528,1.542,1.58,1.138,1.288
155,Sierra Leone,3.802,4.916,5.007,4.252,3.855,3.713,4.085,4.119,4.202,4.407
156,Singapore,295.093,307.576,314.864,307.999,318.753,343.332,375.963,374.39,339.981,378.645
157,Slovakia,94.589,98.878,101.351,88.512,89.691,95.411,105.574,105.131,104.491,116.748
158,Slovenia,46.607,48.416,50.01,43.112,44.754,48.572,54.188,54.185,53.547,60.89
159,Solomon Islands,1.191,1.285,1.338,1.311,1.381,1.458,1.566,1.579,1.562,1.649
160,Somalia,3.611,3.892,3.964,4.049,4.198,4.509,4.651,5.061,4.99,5.424
161,South Africa,434.4,400.877,381.195,346.663,323.493,381.317,404.673,387.849,335.344,415.315
162,South Sudan,11.267,14.947,15.383,14.801,3.501,3.495,4.659,4.589,4.44,3.263
163,Spain,1325.583,1355.162,1371.576,1195.721,1232.573,1312.076,1421.639,1393.2,1280.459,1439.958
164,Sri Lanka,68.381,74.253,79.312,80.557,82.39,87.422,87.922,83.978,80.7,80.785
165,Sudan,48.948,52.892,60.726,64.536,64.883,47.837,33.432,33.564,34.396,35.919
166,Suriname,5.332,5.51,5.612,5.126,3.317,3.592,3.996,3.984,2.884,2.817
167,Sweden,552.484,586.842,581.964,505.104,515.655,541.019,555.455,533.88,541.064,622.365
168,Switzerland,692.382,713.232,734.703,702.195,695.434,704.758,736.089,732.492,751.877,810.83
169,Syria,0,0,0,0,0,0,0,0,0,0
170,Sao Tome and Principe,0.253,0.303,0.349,0.318,0.348,0.376,0.416,0.431,0.477,0.534
171,Taiwan,495.61,512.943,535.328,534.515,543.081,590.733,609.198,612.168,668.156,785.589
172,Tajikistan,7.592,8.506,9.242,7.857,6.953,7.144,7.52,8.117,7.997,8.104
173,Tanzania,39.651,45.681,50.002,47.384,49.774,53.227,56.699,60.81,64.403,69.238
174,Thailand,397.722,420.364,407.373,401.142,413.497,456.523,506.403,544.21,501.712,546.223
175,Timor-Leste,1.148,1.396,1.447,1.594,1.651,1.599,1.56,2.018,1.777,1.697
176,Togo,5.229,5.831,6.174,5.641,6.03,6.393,7.115,7.221,7.586,8.493
177,Tonga,0.471,0.451,0.44,0.437,0.421,0.46,0.486,0.517,0.499,0.501
178,Trinidad and Tobago,25.763,27.268,27.616,24.96,22.394,22.385,23.68,23.208,21.587,21.599
179,Tunisia,45.044,46.248,47.634,43.172,41.801,39.627,40.139,39.169,39.219,42.733
180,Turkey,880.141,957.504,938.512,864.071,869.28,858.932,779.694,760.516,719.919,795.952
181,Turkmenistan,51.756,53.124,57.897,42.162,38.502,41.385,40.762,46.264,45.609,53.087
182,Tuvalu,0.039,0.039,0.039,0.037,0.041,0.045,0.048,0.054,0.055,0.065
183,Uganda,30.939,32.331,33.122,27.445,29.598,31.398,34.223,38.001,38.141,43.243
184,Ukraine,175.707,179.574,130.571,90.477,93.313,112.114,130.916,153.997,155.3,181.038
185,United Arab Emirates,374.591,390.108,403.137,358.135,357.045,385.605,422.215,417.216,358.869,410.158
186,United Kingdom,2704.498,2785.062,3067.117,2933.433,2703.242,2664.705,2860.982,2833.301,2709.678,3108.416
187,United States,16253.95,16843.225,17550.675,18206.025,18695.1,19479.625,20527.15,21372.6,20893.75,22939.58
188,Uruguay,55.692,62.499,62.178,57.874,57.237,64.234,64.766,61.931,56.577,60.108
189,Uzbekistan,67.52,73.192,80.848,85.662,85.658,61.018,52.618,59.907,59.928,65.503
190,Vanuatu,0.736,0.755,0.774,0.744,0.775,0.88,0.928,0.928,0.932,0.999
191,Venezuela,352.191,258.993,203.822,323.595,279.249,143.841,98.4,63.96,47.255,44.893
192,Vietnam,195.169,212.728,232.888,236.795,252.146,277.071,303.091,327.873,343.114,368.002
193,West Bank and Gaza,12.208,13.516,13.99,13.972,15.405,16.128,16.277,17.134,15.561,17.343
194,Yemen,35.401,40.415,43.229,42.444,31.318,26.842,21.606,21.888,18.841,19.471
195,Zambia,25.502,28.042,27.145,21.245,20.965,25.874,26.312,23.309,19.319,21.699
196,Zimbabwe,17.115,19.091,19.496,19.963,20.549,22.041,23.516,19.587,21.924,25.791
197,Africa,2424.463,2502.527,2584.357,2353.868,2237.952,2257.39,2405.657,2473.202,2391.75,2687.173

In [84]:
del df_tmp

---

#### Now, we have completed our data pre-processing for all the datasets and the data is now ready to be loaded into a **_SQL Database_**

---
---

## 3. Store the datasets in SQL Database Server

To store the cleaned data in a SQL database server, we perform the following steps:
1. login and establish connection to a database.
2. create all the required tables with the appropriate data types.
3. store the data in the database server.

### Connect and login into MySQL database server

In [85]:
import mysql.connector
from getpass import getpass

In [86]:
connection = mysql.connector.connect(user=input("Enter username: "), password=getpass("Enter password: ")) 

cursor = connection.cursor()

Enter username: root
Enter password: ········

### Create and Select Database

In [87]:
# Create Database "olympic"

create_db_query = "CREATE DATABASE IF NOT EXISTS olympic"

cursor.execute(create_db_query)

In [88]:
# Check if database is created or not

show_db_query = "SHOW DATABASES"
cursor.execute(show_db_query)

for db in cursor:
    print(db)

('birthdate_db',)
('covid_2020',)
('covid_2021',)
('information_schema',)
('mysql',)
('olympic',)
('performance_schema',)
('sys',)

In [89]:
select_db_query = "use olympic"
cursor.execute(select_db_query)

### Create Tables

In [90]:
tables_def = {
"tokyo_olympic_2020" : """
                        CREATE TABLE IF NOT EXISTS tokyo_olympic_2020 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,

                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                    """,

"rio_olympic_2016" : """
                        CREATE TABLE IF NOT EXISTS rio_olympic_2016 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,

                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                """,

"london_olympic_2012" : """
                        CREATE TABLE IF NOT EXISTS london_olympic_2012 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,
                            
                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                        """,

"population" : """
                CREATE TABLE IF NOT EXISTS population (
                    country_name VARCHAR(60) NOT NULL,
                    pop_2020 INT UNSIGNED NOT NULL,
                    pop_2021 INT UNSIGNED NOT NULL,
                    
                    CONSTRAINT uniq_constraint UNIQUE(country_name)
                )
            """,

"covid_and_vac" : """
                    CREATE TABLE IF NOT EXISTS covid_and_vac (
                        country_name VARCHAR(60) NOT NULL,
                        date_reported DATE NOT NULL,
                        cumulative_cases INT UNSIGNED NOT NULL,
                        new_cases INT NOT NULL,
                        cumulative_deaths INT UNSIGNED NOT NULL,
                        new_deaths INT NOT NULL,
                        people_vaccinated INT UNSIGNED NOT NULL,
                        people_fully_vaccinated INT UNSIGNED NOT NULL,
                        
                        
                        CONSTRAINT uniq_constraint UNIQUE(country_name, date_reported)
                    )
                """,

"gdp_value" : """
                CREATE TABLE IF NOT EXISTS gdp_value (
                    country_name VARCHAR(60) NOT NULL,
                    gdp_2012 FLOAT NOT NULL,
                    gdp_2013 FLOAT NOT NULL,
                    gdp_2014 FLOAT NOT NULL,
                    gdp_2015 FLOAT NOT NULL,
                    gdp_2016 FLOAT NOT NULL,
                    gdp_2017 FLOAT NOT NULL,
                    gdp_2018 FLOAT NOT NULL,
                    gdp_2019 FLOAT NOT NULL,
                    gdp_2020 FLOAT NOT NULL,
                    gdp_2021 FLOAT NOT NULL,
                    
                    CONSTRAINT uniq_constraint UNIQUE(country_name)
                )
            """
}

In [91]:
# Create all the tables in the database
for query in tables_def.values():
    cursor.execute(query)

In [92]:
# Show the created tables

show_tbl_query = "SHOW TABLES"
cursor.execute(show_tbl_query)

for tbl in cursor:
    print(tbl)

('covid_and_vac',)
('gdp_value',)
('london_olympic_2012',)
('population',)
('rio_olympic_2016',)
('tokyo_olympic_2020',)

---

### Write the data into the database

In [93]:
for i, row in df_tokyo.iterrows():
    sql = "INSERT INTO tokyo_olympic_2020 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"
    
    cursor.execute(sql,tuple(row))
    
    connection.commit()

In [94]:
for i, row in df_rio.iterrows():
    sql = "INSERT INTO rio_olympic_2016 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [95]:
for i, row in df_london.iterrows():
    sql = "INSERT INTO london_olympic_2012 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [96]:
for i, row in df_population.iterrows():
    sql = "INSERT INTO population (country_name, pop_2020, pop_2021) VALUES (%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [97]:
for i, row in df_covid_vac.iterrows():
    sql = "INSERT INTO covid_and_vac (country_name, date_reported, cumulative_cases, new_cases, \
    cumulative_deaths, new_deaths, people_vaccinated, people_fully_vaccinated) \
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [98]:
for i, row in df_gdp.iterrows():
    sql = "INSERT INTO gdp_value (country_name, gdp_2012, gdp_2013, gdp_2014, \
    gdp_2015, gdp_2016, gdp_2017, gdp_2018, gdp_2019, gdp_2020, gdp_2021) \
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

---
---

### Close the database connection

Finally, we close the database connections.

In [99]:
# Close the database connections
cursor.close()
connection.close()